### ISSUE TITLE
Product Team Discussion to review Testing Ideas

### ISSUE THREAD

**Issue by cleemullins** [BotBuilderCommunity/botbuilder-community-dotnet#101]
[Update at 9:10AM - new Teams link, as I accidentally "ended" the original live event]

Hi All,

On Tuesday May 21st at 9AM PST (4pm UTC) The Bot Framework Team is hosting a discussion around Unit Testing of Bots. This includes
1. Unit Test a dialog
2. Mock's for LUIS Recognizers 
3. e2e Tests for a dialog
4. Recommended flows for using LU files, Bots, and Source Control. 

To join, please use [this teams link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MTM1N2RjZjctMjk3Yi00ODlhLThjMmUtODRjMzY1ZGFjMjFm%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%226564eb17-71bd-4acd-ac6b-9ad7ad57f394%22%7d).  

Our intent is that this will be a collaborative working session, as while we've got many ideas in this space we're also confident there are more ideas to be discussed. 

Thanks!
//Chris

=== Original Post === 
Hi All,

We (the Bot Framework Product team) would like to schedule an hour-long discussion via Teams (or similar) to review the work we're thinking about for Unit Testing. This work includes:
1. Unit Test a dialog
2. Mock's for LUIS Recognizers 
3. e2e Tests for a dialog
4. Recommended flows for using LU files, Bots, and Source Control. 

Is there a time in the next week or two that would work for folks?

**Comment by garypretty** [comment]
Hi @cleemullins. This sounds great. I'm on vacation in the states until 24th, so w/c 27th might be best for me, after 2pm EDT / 11am PST.

Alternatively, if you want to drop me your availability over the next week or so, I will probably be able to find an hour to join a call - would be helpful to have a few options so I can figure something out that works with our plans. 

Thanks and looking forward to it!

**Comment by cleemullins** [comment]
Let see if anyone else chimes in - ideally next week.

**Comment by garypretty** [comment]
@cleemullins OK, no problem. I've just checked and I think the times next week that would work for me would be after 3pm PST on Monday / Tuesday or sometime on Wednesday.

**Comment by szul** [comment]
@cleemullins @garypretty My schedule is pretty open next week 8-4 EST. The following week, I'm also good except for Wednesday.

**Comment by arafattehsin** [comment]
Hello! I am good any day between 12 PM to 5 PM (PST) -- if you have any other suggestions then please let me know so I can manage my schedule accordingly.

**Comment by brianrandell** [comment]
I'm interested. Monday or Tuesday are best. I'll be in London (UTC + 1) all next week so "be kind" :-) I'll do my best to attend. Wednesday on are bad due to speaking engagements.

**Comment by huan** [comment]
It's great to hear that we will have official unit tests for ChatBot & LUIS!

Please count me in if we have any specific email list or discussions, thanks!

**Comment by cloudguy-pro** [comment]
Hi @cleemullins I'd be super interested to join as we are currently working on a lot of production bots for larger companies and would therefore know how to test bots properly...

**Comment by paulio** [comment]
+1, we're automating test scripts for the Bot, LUIS and Bot + LUIS so would be very interested to see what's happening

**Comment by gabog** [comment]
Hi, I setup a call for Tuesday, May 21st at 9 AM PST (sorry, that's the best I could do to accommodate all the different time zones.

You can use [this link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MDBjYmFmNjQtNjE5Mi00ODU5LWEzNWQtNmE2NDhjZTQ3Zjc1%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%220f65454e-84c1-4979-9deb-e7ac73cc3f94%22%2c%22IsBroadcastMeeting%22%3atrue%7d) to join the call.

Thanks!

**Comment by cleemullins** [comment]
Hi All, I've updated the original post with the details: 
1. On Tuesday May 21st at 9AM PST (4pm UTC, assuming my TimeZone math is right)
2. [Teams Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MDBjYmFmNjQtNjE5Mi00ODU5LWEzNWQtNmE2NDhjZTQ3Zjc1%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%220f65454e-84c1-4979-9deb-e7ac73cc3f94%22%2c%22IsBroadcastMeeting%22%3atrue%7d). 

We're looking forward to the discussion.

**Comment by daltskin** [comment]
Can this call be recorded?

**Comment by gabog** [comment]
@daltskin, I'll try to record (if the Teams gods are with me), does this community has some place where I can post the recording after the call?

**Comment by garypretty** [comment]
@gabog you can liaise with me re the recording and we can get it posted somewhere appropriate.

**Comment by cleemullins** [comment]
Hey all - I've updated the Teams link in this thread to [this one](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZGRkZTEzOGItNTYyMS00M2U5LWE1M2ItYzcwYTU5YjEyZjFl%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%220f65454e-84c1-4979-9deb-e7ac73cc3f94%22%2c%22IsBroadcastMeeting%22%3atrue%7d) as I accidently ended the live meeting and @gabog had to create a new one.

**Comment by paulio** [comment]
Is this on now?

**Comment by cleemullins** [comment]
[Updated Teams meeting (take 2)](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MTM1N2RjZjctMjk3Yi00ODlhLThjMmUtODRjMzY1ZGFjMjFm%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%226564eb17-71bd-4acd-ac6b-9ad7ad57f394%22%7d)

**Comment by garypretty** [comment]
I'm not going to make it sadly, but look forward to watching the recording.

**Comment by gabog** [comment]
Hi all, sorry but we run into some technical issues today and we couldn't record the call.

**Comment by garypretty** [comment]
Closing this - I hear the call was of great help and we should see some outputs from the team in the near future.
