### ISSUE TITLE
Twitter Adapter contribution

### ISSUE THREAD

**Issue by tmarkovski** [BotBuilderCommunity/botbuilder-community-dotnet#105]
Hey everyone,

I'd like to contribute some work that I did around integrating Twitter direct messages with the Bot Builder SDK. This is an effort that I did for an ongoing project and I think the community can find some use of it, as it's currently hard to find easy integration between Twitter and Bot Builder.

The work I did is at https://github.com/tmarkovski/bot-builder-twitter-adapter

If you feel this would be something of value for the community, I'd be happy to refactor and submit PR to this repo. I've already made namespacing to roughly match the conventions here.
I open to any changes or additions to it.
I'd like to get your feedback on how best to make the submission.

Cheers,
Tomislav

**Comment by garypretty** [comment]
Hi. Thanks for reaching out with this. This is awesome!! We would love to have this as part of the community.

Please do submit a PR. If you could make sure the readme is as detailed as it can be in terms of setup / usage etc that would be amazing.

Thanks again and welcome to the community!

**Comment by garypretty** [comment]
Closing now that this has been merged. Thanks again.
