### ISSUE TITLE
This is the repo I looking for!!

### ISSUE THREAD

**Issue by baruchiro** [BotBuilderCommunity/botbuilder-community-dotnet#109]
Sorry about the "not valued" issue.

I'm working on my bot a while, and there is in it a solutions I done, and in my mind there is more solutions to develop.

But now, I happened to discover this Repository, and all my solutions are in it!

I think that developers are not familiar with this repository, and maybe a link to the repository should be included in the Microsoft documentation.

**Comment by arafattehsin** [comment]
Hi @baruchiro where were you looking for this? Official docs mentions the name of the community with the link and there's a whole blog post from the Bot Framework team.

**Comment by garypretty** [comment]
Closing this - thank you very much for the feedback. Great to hear the repo is useful!
