### ISSUE TITLE
Alexa Adapter and MS Bot Framework Dialog

### ISSUE THREAD

**Issue by mwnowicki** [BotBuilderCommunity/botbuilder-community-dotnet#110]
Hello,

I would like to use bot dialog with Alexa. Is any way to use Alexa Adapter with Dialog? Do you have sample of this kind of implementation?

Kind Regards,
Maciej

**Comment by garypretty** [comment]
@mwnowicki Can you share more specifics about what you are looking to achieve here?  We do have a sample in place showing how to use the Alexa adapter. Take a look and let us know what's missing if it doesn't solve your problem.

**Comment by mwnowicki** [comment]
@garypretty  I already review samples and some more examples. I was able to make all working. Thanks.
