### ISSUE TITLE
Alexa Adapter - Session Attributes

### ISSUE THREAD

**Issue by mwnowicki** [BotBuilderCommunity/botbuilder-community-dotnet#119]
Hi,

I would like to ask for clarification. In documentation [Session Attributes](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Adapters.Alexa#Session-Attributes), it isn't quite clear if TurnContext parameters are mapped into Session Attributes automatically.

When bot gets request from Alexa then new attributes are added into TurnContext, like here:
![image](https://user-images.githubusercontent.com/38342607/59450875-20a0d200-8e02-11e9-8977-82a2fdb43ae1.png)

When this is send back to Alexa these parameters are not mapped into session attributes:
```
{
	"body": {
		"version": "1.0",
		"response": {
			"outputSpeech": {
				"type": "PlainText",
				"text": "TEXT_TO_SPEECH"
			},
			"card": {
				"type": "Standard",
				"title": "TITLE",
				"text": "TEXT",
				"image": {
					"smallImageUrl": "https://....................jpg",
					"largeImageUrl": "https://....................jpg"
				}
			},
			"directives": [],
			"shouldEndSession": true,
			"type": "_DEFAULT_RESPONSE"
		},
		"sessionAttributes": {}
	}
}
```
Does it means that I need to add code to map parameters from TurnContext and then it will be added as to Session Attributes? My first thought was that all TurnContext parameters are mapped automatically. Could you please clarify?

Regards

**Comment by BeigeBadger** [comment]
@mwnowicki are you using the Virtual Assistant template? Also from your screenshot should you not be inspecting `TurnState[0]` as that looks like to have the key `AlexaSessionAttributes` and the value appears to be a dictionary - which is mentioned in the documentation.

>  We then provide an extension method on the context to allow you to add / update / remove items on the Session Attributes list. Calling the extension method AlexaSessionAttributes returns an object of type Dictionary<string, string>.

**Comment by mwnowicki** [comment]
Hello,

Yes, I'm using Virtual Assistant template which uses OnTurnAsync. 
Solution for this problem was to run "SaveChangesAsync" on states objects:
```
await _conversationState.SaveChangesAsync(turnContext, false, cancellationToken);
await _userState.SaveChangesAsync(turnContext, false, cancellationToken);
```

Regards

**Comment by BeigeBadger** [comment]
Glad to hear it. Did you have any issues with your Alexa responses falling through to the OnInterruptAsync method in MainDialog.cs instead of going into OnRouteAsync like the rest of the messages?

**Comment by mwnowicki** [comment]
Hi @BeigeBadger 

I made extension to 'RouterDialog' class to add some functionality for Alexa messages. However messages goes to 'OnInterruptAsync' method first and later to 'OnRouteAsync'.

Regards

**Comment by BeigeBadger** [comment]
Thanks for the reply @mwnowicki. Did your messages automatically fall through to `RouteAsync` after going through `OnInterruptAsync`? I had to call `RouteAsync` manually from within `OnInterruptAsync`.

**Comment by mwnowicki** [comment]
Hi @BeigeBadger 

Please download source code for 'RouterDialog' then you will see that this functionality is defined there. I made extension to that class but you can have a different solution based on your needs.

Regards
