### ISSUE TITLE
Feature Request: Currency prompt

### ISSUE THREAD

**Issue by martinkearn** [BotBuilderCommunity/botbuilder-community-dotnet#12]
This is a feature request.

I'd love to a see a Dialog/Prompt for capturing and validating Currency inputs from the user. The closest we have is `NumberPrompt` but that only returns and `Int` which is not great for currency.

I'd like something like the `NumberPrompt` which returns a `Double` (chose a double because Luis returns a double for money entities so it will be consistent).

If I get time to do this myself, I may add it to this repo but wanted to log the feature in case anyone else is looking for something to do ;)

**Comment by garypretty** [comment]
Great idea. I'd like to see this too and is on my backlog - I will try and work something up for this over the weekend. I might put it straight into our branch which is tracking latest, rather than building for preview as the dialog / prompt APIs have changed significantly. I'll let you know once I have something!

**Comment by garypretty** [comment]
@martinkearn first iteration of the prompt completed.  Right now it should be able to handle input such as "50 dollars", "fifty five pounds" or "£50.50".  I still need to figure out if I can combine multiple resolutions, such as "fifty five pounds and fifty pence", but I suspect that might be a bit more complex - anyway, this should be a good start.

Would love you to take a look and let me know what you think.  You can take a look at [CurrencyPrompt.cs](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/currency-prompt/libraries/Bot.Builder.Community.Dialogs.Prompts/CurrencyPrompt.cs)
 and also the associated [Unit tests](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/currency-prompt/tests/Bot.Builder.Community.Dialogs.Prompts.Tests/Currency_PromptTests.cs).

**Comment by garypretty** [comment]
@martinkearn as a quick note following up on this - I wanted to point out that rather than simply return a double from the prompt, I am returning a CurrencyPromptResult object, which has two properties.  

- Value (type double)
- Unit (type string)

**Comment by garypretty** [comment]
@martinkearn further update :) I have now removed the CurrencyPrompt, but added a new NumberWithUnitPrompt which allows you to specify the type of number / unit you are looking for.  It supports currency, temperature, age and dimension (e.g. mile, meter etc).

You can see the usage in the new [unit test file](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/currency-prompt/tests/Bot.Builder.Community.Dialogs.Prompts.Tests/NumberWithUnit_PromptTests.cs)

cc @szul @jamesemann

**Comment by garypretty** [comment]
@martinkearn I am going to close this issue for now, as the new NumberWithUnit prompt is now part of the repo and available via NuGet. Feel free to reopen if needed.
