### ISSUE TITLE
Adapters.Google missing UTF-8 charset in response?

### ISSUE THREAD

**Issue by sremy91** [BotBuilderCommunity/botbuilder-community-dotnet#123]
Hi,
I encounter issues on google home side. I built a MS Bot using the Google Adapter, the bot is dedicated to french local (fr-FR).

From time to time, on Google Simulator or on Google Assistant Device, some accents are misinterpreted "OÃ¹ sallez-vous?" instead of "Où allez-vous?" 

I found that in /Integration/AspNet.Core/GoogleHttpAdapter.cs, the ContentType of the Response sent to Google is set to "application/json".

I tried to set it to "application/json;charset=utf-8" and it seems to work in a stable way, characters are always recognized.

Is that a bug to be fixed or am i the only one to encounter that?

**Comment by garypretty** [comment]
Thanks for the heads up - I will get a fix in for this.

**Comment by garypretty** [comment]
PR raised #192 - this will go out in the next release.  Also updated in the new adapter preview to ensure this fix makes it into that as well.  @sremy91 thanks again for the heads up.
