### ISSUE TITLE
Adapters.Alexa missing escape for ampersand in SSML response

### ISSUE THREAD

**Issue by Mando-Henry** [BotBuilderCommunity/botbuilder-community-dotnet#129]
Using an ampersand in a response results in the following (as I believe '&' isn't supported in SSML):

Invalid SSML Output Speech for requestId XXXXXXXX. Error: Fatal error occured when processing SSML content. This usually happens when the SSML is not well formed. Error: Unexpected character ' ' (code 32) (missing name?)\n at [row,col {unknown-source}]: [1,XX]

Replacing the '&' with 'and' fixes this, but it'd be nice to do this by default. As this is only for speech and not text (so '&' and 'and' are equivalent), it's probably best to build in a straight swap.

**Comment by arafattehsin** [comment]
Thanks for pointing out. I'll try to fix it by the end of this weekend!

**Comment by garypretty** [comment]
Hey @arafattehsin - that last push to master does not contain this fix - I am reviewing this fix to see if we need to do something wider.  @Mando-Henry has implemented a local fix in the meantime.  I'll come back to this once I have reviewed.
