### ISSUE TITLE
[Question] How to implement Transcript store on Twitter Adapter

### ISSUE THREAD

**Issue by fercom** [BotBuilderCommunity/botbuilder-community-dotnet#141]
How do I implement a transcript logger on the  [twitter adapter](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Adapters.Twitter)?, I am using [Entity framework transcript store](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Storage.EntityFramework) but I am only able to store outgoing messages with the following code:
`((TwitterAdapter)_adapter).ContinueConversationAsync(_appId, conversationReference, BotCallback, default(CancellationToken));`
and not able to store incoming messages, how can I do it?

**Comment by tmarkovski** [comment]
You can register middleware for use with any adapter by calling `Use(<IMiddleware>)`.
That said, in your Startup.cs inside `Configure(IApplicationBuilder app` you can potentially do

        app.ApplicationServices.GetRequiredService<TwitterAdapter>().Use(
            app.ApplicationServices.GetRequiredService<TranscriptLoggerMiddleware>());

I haven't tested this, but if `TranscriptLoggerMiddleware` resolves from the services, it will be added to the pipeline and should store the incoming messages.

**Comment by fercom** [comment]
I registered inside the constructor of TwitterAdapter, is there any difference?

**Comment by tmarkovski** [comment]
No difference, as long as it works.

**Comment by fercom** [comment]
But it doesnt 😔... And the middleware is registered, i can see it while debugging

**Comment by tmarkovski** [comment]
Quickly looking at the code, it appears we need to call `RunPipelineAsync` inside `Webhook Middleware`, instead calling the `TurnContext.OnTurnAsync` directly. Should be a quick and easy change. I'll push a PR today.

**Comment by fercom** [comment]
Ok, thanks, would you please let me know when you do it? ☺

**Comment by iMicknl** [comment]
@tmarkovski what about using `ProcessActivity` like in the other adapters? ([Alexa example](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Alexa/AlexaAdapter.cs#L36)). From there you can create the `TurnContext` and call `base.RunPipelineAsync`.

**Comment by tmarkovski** [comment]
@iMicknl That's a good pattern and keeps things consistent. I'll move the logic over to the adapter.

**Comment by fercom** [comment]
@tmarkovski where should I call `RunPipelineAsync`? It seems that it needs a callback as an argument but I dont know where to find it

**Comment by mdrichardson** [comment]
@iMicknl @tmarkovski Any further guidance on how to do this? I've been toying with it quite a bit and can't seem to get it working (pretty new to DI and Middleware, admittedly). Seems like the `TwitterAdapter` is overwriting the `AdapterWithErrorHandler`. I can't really find a quick fix...seems like the "easiest" way is to rewrite most of the adapter to be more in line with the others. Am I missing something?

**Comment by cleemullins** [comment]
As an aside, we've got a pattern we're using for our new Adapters (Twilio, WebEx, Slack, Teams, etc) that may be applicable to this adapter. I suspect we'll end up writing hybrid / composite adapters as well for bots that support multiple channels...

**Comment by fercom** [comment]
Hi @tmarkovski , any update on this? Thanks!

**Comment by tmarkovski** [comment]
@fercom The PR is up. I've modified the code slightly to follow similar patterns as the existing adapters.

**Comment by fercom** [comment]
@tmarkovski ok, it looks like the merge is blocked

**Comment by fercom** [comment]
@tmarkovski now that the update is done I tested this code but it doesn't work, it says: **No service for type 'Microsoft.Bot.Builder.TranscriptLoggerMiddleware' has been registered.** Any Idea?

> 
> 
> You can register middleware for use with any adapter by calling `Use(<IMiddleware>)`.
> That said, in your Startup.cs inside `Configure(IApplicationBuilder app` you can potentially do
> 
> ```
>     app.ApplicationServices.GetRequiredService<TwitterAdapter>().Use(
>         app.ApplicationServices.GetRequiredService<TranscriptLoggerMiddleware>());
> ```
> 
> I haven't tested this, but if `TranscriptLoggerMiddleware` resolves from the services, it will be added to the pipeline and should store the incoming messages.

**Comment by tmarkovski** [comment]
@fercom I believe the middleware and adapters should be resolved within a [scoped lifetime](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2#scoped). The problem here doesn't seem to have anything to do with the adapter, but rather how you resolve `TranscriptLoggerMiddleware`.

**Comment by fercom** [comment]
@tmarkovski Ok, thanks, it is working now with the last nuget version (4.5.6).

For future references:
in the ConfigureServices Method you must have this:
```
  var store = new EntityFrameworkTranscriptStore(connection);
            services.AddSingleton<ITranscriptStore>(store);
```

and the Configure method must be something like this:
  ```
   public void Configure(IApplicationBuilder app, IHostingEnvironment env, ITranscriptStore transcriptLogger)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }

            app.UseDefaultFiles();
            app.UseStaticFiles();

            //app.UseHttpsRedirection();
            app.UseMvc();
            app.UseTwitterAdapter();

            app.ApplicationServices.GetRequiredService<TwitterAdapter>().Use(new TranscriptLoggerMiddleware(transcriptLogger));
        }
```
