### ISSUE TITLE
[Twitter Adapter] Failed to register subscription...

### ISSUE THREAD

**Issue by mdrichardson** [BotBuilderCommunity/botbuilder-community-dotnet#143]
I must be doing something wrong in setting up my Twitter dev account, because for the life of me, I can't seem to get around this error:

```
Failed to register subscription: 170: Webhook URL must be defined to create subscriptions.
```

I've tried various combinations of `TwitterOptions` and API settings, but here's what I have up currently:

```json
  "TwitterOptions": {
    "WebhookUri": "https://******.ngrok.io/adapter/twitter",
    "AccessSecret": "Nfx6V6rYrdoBwZG***************",
    "AccessToken": "116388243778228****************",
    "ConsumerKey": "Ewp0RIpWtrAbK***************",
    "ConsumerSecret": "s6PGpfMCZUDRRTQaVgnJzAtTdui***************",
    "Environment": "vmicricdev",
    "Tier": "PremiumFree",
    "BotUsername": "@MicricV",
    "AllowedUsernames": []
  }
```

![image](https://user-images.githubusercontent.com/40401643/63389602-1a2e5980-c361-11e9-9d11-f298228fd309.png)

![image](https://user-images.githubusercontent.com/40401643/63389640-3c27dc00-c361-11e9-8e05-24553991ce74.png)

![image](https://user-images.githubusercontent.com/40401643/63389674-56fa5080-c361-11e9-83c3-80fe018cd795.png)

![image](https://user-images.githubusercontent.com/40401643/63389683-5c579b00-c361-11e9-8173-b55846bd27e4.png)

Any idea what I'm doing wrong?

**Comment by tmarkovski** [comment]
@mdrichardson Everything looks good. Is your account on the Premium tier or Enterprise? The API's are slightly different for both and I think the code we have here is configured for Premium tier.

**Comment by mdrichardson** [comment]
@tmarkovski I'm using `PremiumFree`. Super new to Twitter dev...just doing this for some testing and haven't paid for anything; is that the problem?

Here's my console output:

```cmd
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 DEBUG http://localhost:55986/  0
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:55986/  
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\2.2.6\Microsoft.AspNetCore.Http.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\2.2.6\Microsoft.AspNetCore.WebUtilities.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 53.9451ms 200 
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware:Information: The file /default.htm was not modified
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 73.7904ms 304 text/html
Bot.Builder.Community.Twitter.Adapter.Hosting.WebhookHostedService:Information: Webhook not found. Registering [https://c86b773e.ngrok.io] for [vmicricdev]
Bot.Builder.Community.Twitter.Adapter.Hosting.WebhookHostedService:Error: Failed to register subscription: 170: Webhook URL must be defined to create subscriptions.
The program '[6332] dotnet.exe: Program Trace' has exited with code 0 (0x0).
The program '[6332] dotnet.exe' has exited with code -1 (0xffffffff).
```

Let me know if you want me to do any additional testing. Happy to help out.

**Comment by mdrichardson** [comment]
Well, that's embarrassing. Turns out the issue was that I had an [Azure Relay](https://blog.botframework.com/2019/04/16/debugging-your-locally-hosted-v4-bot-using-azure-relays/) running in the background on the same port and it was conflicting with ngrok. It works now. Hope you didn't spend as much time on this as I did 🤦‍♂️
