### ISSUE TITLE
Formflow data gets recreated on successive calls (call to 2nd step) to form steps 

### ISSUE THREAD

**Issue by paul198204** [BotBuilderCommunity/botbuilder-community-dotnet#144]
Hi,
We are using Bot Frmaework V3 and planning for migration to V4. We use form for many flows in our Bot and the forms expects parameter in constructor (Ex: RequestForm(Data data)).

With V4, looks like Bot.Builder.Community.Dialogs.FormFlow forms gets re-instantiated as part of dialog context creation while going through the form build steps which is making Data to reconstructed on every call to form step and it is causing issues. Any Idea on how to resolve this?

Thanks,
Praveen V

**Comment by paul198204** [comment]
Just to add more information on this, I see dialog state is changed with call to await m_conversationState.SaveChangesAsync(turnContext, false, cancellationToken); after 1st question of formsflow form. But when User answer for it, on creation dialog context in OnMessageActivityAsync., I see turn context does not have the previous state  and on trying to load state from storage (I am using Memory Storage for testing) it tries to recreate (use default values) which is not expected as the values are passed in form constructor. This looks like state handling issue but am not sure how to fix this

**Comment by paul198204** [comment]
After 1st Question of Formsflow form - while saving state
![image](https://user-images.githubusercontent.com/13347968/63641948-d6429980-c66b-11e9-88c7-77eaf383c8dc.png)

After user types in message for 1st question - while handling user message
![image](https://user-images.githubusercontent.com/13347968/63641957-fd996680-c66b-11e9-9e78-32b5ac009c2a.png)

**Comment by garypretty** [comment]
Quick update on this - we are hoping to get to this issue in the first half of November if nobody picks it up in the meantime.
