### ISSUE TITLE
Bot.Builder.Community.Dialogs.FormFlow.FormDialog<T> extends ComponentDialog without calling base.BeginDialogAsync

### ISSUE THREAD

**Issue by v-kydela** [BotBuilderCommunity/botbuilder-community-dotnet#151]
Overriding `ComponentDialog.BeginDialogAsync` without calling the base implementation means `PersistedDialogState` never gets initialized which can lead to exceptions like these: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/issues/148

My feeling is that `FormDialog<T>` should just extend `Dialog` instead of `ComponentDialog`.

**Comment by garypretty** [comment]
Closing this. Many people are using this package without issue currently and I would rather not change the implementation unnecessarily.  We can revisit if further issues become apparent.
