### ISSUE TITLE
WeChat Adapter

### ISSUE THREAD

**Issue by techie921** [BotBuilderCommunity/botbuilder-community-dotnet#152]
Hi Team,

I am planning to develop the WeChat Adapter. 
Can you please help how to start developing?
If you have any sample code for WeChat, please share with me

Thanks,
Sakru Jarpula.

**Comment by garypretty** [comment]
Hi @techie921 - it appears this has already been done, or is at least underway, within the Microsoft SDK - see https://github.com/microsoft/botbuilder-dotnet/pull/2217

**Comment by arafattehsin** [comment]
Closing this issue as it's already in the pipeline. Thank you for your interest @techie921. Please do not hesitate to contribute in other adapters / extensions.
