### ISSUE TITLE
LocationDialog wants a full BotState object in its constructor

### ISSUE THREAD

**Issue by JeffCordes** [BotBuilderCommunity/botbuilder-community-dotnet#159]
It should only get an IStatePropertyAccessor to a specific property on the state.

**Comment by garypretty** [comment]
Hey @JeffCordes. Thanks for raising the issue.  I am not sure I totally agree with this.  The intention was to make life as easy as possible for a developer and not have them need to create the accessor, but simply pass in their bot state object.

This dialog was written a good while ago now, before DI was property implemented / used, so it is now fairly common to pass in Conversation / User state using DI into a dialog and have the dialog create the required accessor itself.

I will consider this more closely though - we will be having a sprint of activity shortly to update samples, docs etc. and as part of this I will be revisiting the LocationDialog to ensure it is aligned to the latest patterns in the SDK.

Thanks again for the issue!

**Comment by JeffCordes** [comment]
Thanks Gary.

FWIW, my concern with using the a full bot state object has to do with test-ability.   You can not mock a BotState for a unit test, but you can mock and setup an IStatePropertyAccessor<T>.  

Whatever way you chose to go, perhaps some unit tests around this dialog in this source code that would both ensure it is tested, and provide a sample to end users of how to write unit tests on code that contains it would be a big help.

Thanks for contributing to the community!

**Comment by garypretty** [comment]
Thanks @JeffCordes. I absolutely want to get more tests in place.  In terms of testability, on the SDK team we actually use MemoryStorage in most cases, along with a test adapter, in order to test things like this, which means we don't need to mock the state. I've been pretty busy last couple of months with joining the SDK team, but it is high on my priorities to significantly increase certain elements within this repo, with testing being a key one.

**Comment by garypretty** [comment]
I am closing this, as I think we have addressed the core issue of not altering the behavior of passing botstate.  Testing being improved is an all up wider goal for this repo.
