### ISSUE TITLE
Port existing samples to MVC

### ISSUE THREAD

**Issue by arafattehsin** [BotBuilderCommunity/botbuilder-community-dotnet#163]

**Comment by garypretty** [comment]
@arafattehsin Thanks for raising this.  It is sensible.  Maybe as you are going to work on a sample, create a specific issue for it and link it here.  This way we don't step on each other - I am planning to do some work on Alexa / Google / Twitter docs and samples in the very near term.

**Comment by arafattehsin** [comment]
Thank you @garypretty for the advice. I agree with you. 

I will start from Sentiment Analysis Middleware sample (and will start raising issues as I pick one).

**Comment by garypretty** [comment]
@arafattehsin I am going to close this issue.  Over the coming weeks / months the plan is to ensure focus is on Composer scenarios.  We may even decide to archive some of the community samples / packages, but no clear plan yet. I'll reach out offline with more details and to sync on thoughts.
