### ISSUE TITLE
Add StyleCop / FxCop rule to the repo

### ISSUE THREAD

**Issue by garypretty** [BotBuilderCommunity/botbuilder-community-dotnet#164]
I would like to mirror the rules used within the Bot Builder SDK repo (at least the majority of them) that @gabog has done a fabulous job of pushing. We will need to do this over time, as it is going to take a significant amount of effort to adopt these rules.  It may be that I work on this project by project / sample by sample and enable the rules in each as I re-visit them.

**Comment by garypretty** [comment]
Added stylecop rules in PR #171. All stylecop rules shown as warnings.  WarningsAsErrors will be enabled per project as warnings corrected. @arafattehsin If you make any changes on any projects, please try and do a pass and fix as many warnings as you can. Thanks.

**Comment by arafattehsin** [comment]
Sure @garypretty, noted!
