### ISSUE TITLE
Alexa Adapter - ShouldEndSession

### ISSUE THREAD

**Issue by joe-tossell-mando** [BotBuilderCommunity/botbuilder-community-dotnet#168]
ShouldEndSession should be set to null for certain directives but the adpater always sets this value. I've encountered this issue particularly when adding a VideoDirective. The issue is also documented here:
https://github.com/timheuer/alexa-skills-dotnet/issues/166

Am unable to find Amazon documentation specifying this.

**Comment by stoiveyp** [comment]
FYI, if the adoption of Alexa.NET gets merged in - I've just submitted a fix by allowing Directives to identify a required ShouldEndSession value

https://github.com/timheuer/alexa-skills-dotnet/pull/188

**Comment by garypretty** [comment]
@stoiveyp Thanks for letting us know about this and for the fix. I'll remove the workaround we have in the adapter for this.

**Comment by garypretty** [comment]
@joe-tossell-mando The PR in Alexa.Net (https://github.com/timheuer/alexa-skills-dotnet/pull/188) has been merged.  Awaiting a release so we can utilise in the updated adapter.

**Comment by garypretty** [comment]
This has now been added into the Alexa preview package and will be released over the next couple of weeks. Thanks for reporting @joe-tossell-mando and for your help @stoiveyp!
