### ISSUE TITLE
Feature Request: Keyword extraction Middleware

### ISSUE THREAD

**Issue by stephanbisser** [BotBuilderCommunity/botbuilder-community-dotnet#17]
This is a feature request to log a new feature.

There should be a Middleware component in order to extract keywords of an incoming message and log/store them somewhere (Table Storage, Cosmos DB, ...)

**Comment by garypretty** [comment]
Closing this as it hasn't been actioned / commented in a while.  Please re-open if you still need it, or better still contrib :)
