### ISSUE TITLE
Feature Request: Microsoft Graph Middleware

### ISSUE THREAD

**Issue by stephanbisser** [BotBuilderCommunity/botbuilder-community-dotnet#18]
A Microsoft Graph Middleware would be useful to run operations against the Graph to get details about users, current emails, files, ...

**Comment by cleemullins** [comment]
There is an [ADD/MSGraph Bot Sample] sample (https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/24.bot-authentication-msgraph) that's pretty close to what's you're asking. The sample has implementations in both C# and Node. 

The sample is a demonstration of using the OAuth prompts, getting the relevant AAD token, and making queries against the graph. 

The sample, however, is *not* Middleware, which could be quite interesting. The work to adapt the msgraph sample to be middleware wouldn't be too hard. The harder question is what problem would you want to be solving in the Middleware? If you reach out to MSGraph on every turn, the latency penalty will be non-trivial. Figuring out how to only make those calls when needed, and still have it be part of the Middleware, might be tough. 

One example could be "Send me a Transcript". That is, on some trigger (time / message count / conversation end / etc), push the chat transcript into the graph as an email message or similar.

**Comment by cleemullins** [comment]
@jamesemann Ah. Yes, if there was a user profile (RDF?) store hanging off the MSGraph into which you could assert facts that would be fun. One day, my dream of a user profile store (RDF, OWL, RDFS, etc) hosted in an Azure subscription, into which facts could be asserted and queries could be run will be a reality...

**Comment by cloudguy-pro** [comment]
@cleemullins you are right about the fact that it is probably not the beste option to call the Graph on every turn. It would be better to host this as a service like implementation and just call it when needed. I‘m also thinking of doing dialogs which call the graph for things like polling emails, creating SharePoint sites or Teams teams etc...

**Comment by garypretty** [comment]
@cloudguy-pro @jamesemann can I suggest, if you haven't seen it already, checking out the code within https://github.com/Microsoft/AI/tree/master/solutions/Virtual-Assistant.  They have the idea of skills that can be snapped into a bot - they are essentially collections of dialogs and many of them use the Graph.  They have some good approaches to calling the graph, managing auth etc so might be worth checking out so we are not re-inventing the wheel or you at least have a head start.

**Comment by garypretty** [comment]
Closing this as it hasn't been actioned / commented in a while.  Please re-open if you still need it, or better still contrib :)
