### ISSUE TITLE
middlewares

### ISSUE THREAD

**Issue by Hellitself** [BotBuilderCommunity/botbuilder-community-dotnet#180]
Greetings BotCommunity,

first of all, much thanks for your Bot.Builder.Community.Adapters.Twitter.

i am having an issue with the adapter as follows:
when adapter is done receiving and parsing the message, it calls straight up _Bot.OnTurnAsync
meaning, that it skipped all other middlewares i have in my solution, which is causing a problem.

any idea how could this be improved in such it will call middlewares i have in my startup.cs file after twitter adapter is done.

thanks in advance

**Comment by garypretty** [comment]
@Hellitself thanks for the feedback.  A review of the Twitter adapter is on our backlog, but I will take a look at this issue specifically and come back to you.

**Comment by haitham-shaddad** [comment]
@garypretty  I will have a look at this one if you have not fixed it already.

**Comment by garypretty** [comment]
@haithad-shaddad yes please that would be awesome. Thanks for the offer. More contributors are always welcome and great to see!

**Comment by garypretty** [comment]
Closing. This will be handled as part of #301
