### ISSUE TITLE
Reading from ElasticsearchStorage storage don't not work (no such index)

### ISSUE THREAD

**Issue by sawmixer** [BotBuilderCommunity/botbuilder-community-dotnet#181]
Hello.
I check scenario of storage usage from
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp

**Expected result (work with MemoryStorage):**
Bot: Hello and welcome!
Me: Hello
Bot: 1: The list is now: Hello
Me: world
Bot: 2: The list is now: Hello, world

**Actual result:**
Bot: Hello and welcome!
Me: Hello
Bot: 1: The list is now: Hello
Me: world
Bot: 1: The list is now: world

**Preconditions:**
EchoBot sample (SHA-1: c1e2eabeccac2c544e0c1dbac3f0fe92fd66bb6c)
Microsoft.Bot.Builder v4.6.3
Bot.Builder.Community.Storage.Elasticsearch v4.6.3
Elasticsearch v7.5.0

```csharp
    public class EchoBot : ActivityHandler
    {
        // Create Storage.
        private static readonly ElasticsearchStorage _myStorage = new ElasticsearchStorage(new ElasticsearchStorageOptions()
        {
            ElasticsearchEndpoint = new System.Uri("http://localhost:9200"),
            IndexMappingDepthLimit = 100000,
            IndexName = "bot-data"
        });
...
```

**Debugging:**
In ElasticsearchStorage.ReadAsync

searchResponse.ServerError:
`{404Type: index_not_found_exception Reason: "no such index [bot-data]"}`

searchResponse.DebugInformation:
```
Invalid NEST response built from a unsuccessful low level call on POST: /bot-data/documentitem/_search?typed_keys=true
# Server indicated deprecations:
- 299 Elasticsearch-7.5.0-e9ccaed468e2fac2275a3761849cbee64b39519f "[types removal] Specifying types in search requests is deprecated."
# Audit trail of this API call:
 - [1] BadResponse: Node: http://localhost:9200/ Took: 00:00:00.0044912
# OriginalException: Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 404 from: POST /bot-data/documentitem/_search?typed_keys=true. ServerError: Type: index_not_found_exception Reason: "no such index [bot-data]"
# Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# Response:
<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
```

searchResponse.ApiCall.Uri:
`{http://localhost:9200/bot-data/documentitem/_search?typed_keys=true}`

searchResponse.Documents.Count:
`0`

Document in Elasticsearch index wtites/rewrites correctly, I think:
```json
{
  "_index": "bot-data-12-09-2019",
  "_type": "documentitem",
  "_id": "UtteranceLog",
  "_version": 2,
  "_score": null,
  "_source": {
    "id": "UtteranceLog",
    "realId": "UtteranceLog",
    "document": {
      "$type": "Microsoft.BotBuilderSamples.Bots.EchoBot+UtteranceLog, EchoBot",
      "UtteranceList": {
        "$type": "System.Collections.Generic.List`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib",
        "$values": [
          "world"
        ]
      },
      "TurnNumber": 1,
      "ETag": "*"
    },
    "timestamp": "2019-12-08T20:14:38.0647776Z"
  },
  "fields": {
    "timestamp": [
      "2019-12-08T20:14:38.064Z"
    ]
  },
  "sort": [
    1575836078064
  ]
}
```

**PS:**
I tried replacing
elasticClient.SearchAsync<DocumentItem>(s => s.Index(indexName) to
elasticClient.SearchAsync<DocumentItem>(s => s.Index(indexName+"*")
into ElasticsearchStorage.ReadAsync method,
because this request work http://localhost:9200/bot-data*/documentitem/_search?typed_keys=true
but this leads to an deserialization error

**Comment by garypretty** [comment]
Hopefully this issue should be resolved from the PR just merged to update to 7.x - #233
