### ISSUE TITLE
Question how to ShouldEndSessionByDefault to false for singular response for alexa adapter

### ISSUE THREAD

**Issue by JaredLLewis** [BotBuilderCommunity/botbuilder-community-dotnet#183]
Using .NET core 2.0 on version 4.5.3:
I know I can set this value in startup.cs to false to have one persistent conversation but not sure how to set this value for one time when startup has it set to true. I tried using:
turnContext.Activity.AsMessageActivity();
turnContext.Activity.InputHint = "acceptingInput";
and then using the async send activity to send a message, however, the alexa response is still true for this value.

**Comment by garypretty** [comment]
@JaredLLewis Send an InputHint of 'AcceptingInput' will just fallback to the adapter default.  If you want to explicity override the adapter, you can send 'ExpectingInput' to leave the conversation open, or 'IgnoringInput' to close the conversation, depending on your needs.  Hope that helps.

**Comment by garypretty** [comment]
Closing this. Please re-open if the advice above doesn't fix your issue. Thanks.
