### ISSUE TITLE
Google adapter doesn't convert SuggestedActions in outgoing activity

### ISSUE THREAD

**Issue by gmajian** [BotBuilderCommunity/botbuilder-community-dotnet#188]
In README.md it mentions "Automatic conversion of Suggested Actions into Google Suggestion Chips". As I tested, it doesn't work. I also found the cause of the bug. Will submit PR soon.

**Comment by arafattehsin** [comment]
Thank you @gmajian for the contribution.

**Comment by garypretty** [comment]
@gmajian Thanks again for the contrib.  This has been merged. An updated release should be available in the next 24 hours. Thanks.

**Comment by marcasmar94** [comment]
@garypretty will the Twitter adapter be getting any updates soon ?
