### ISSUE TITLE
GOOGLE ADAPTER - Distinguish between a Google Home Device and Google Assistant App 

### ISSUE THREAD

**Issue by aishwaryaumachandran** [BotBuilderCommunity/botbuilder-community-dotnet#194]
We have enabled the account linking feature in Google Actions. When we tried publishing the Bot, we came across the issue of linking the account via the trigger "Link my account" 

We currently want to distinguish the channel name in the TurnContext to identify if it is from a Google Assistant app or a Google Home device. If it is from a google assistant app, a redirect URL can be provided versus the Google Home Device would have a standard message to link the account from the Assistant App and cancels the conversation.

**Comment by garypretty** [comment]
The full request from Google is available within the activity.ChannelData property, which contains information you can use to determine what capabilities the user's device has (you cannot tell the exact device type, but you can see if they have audio / visual capabilities etc.).

There are a couple of extension methods for the turn context to help you here, so you could do;

This one will return a list of capabilities.  For more information about capabilities, see https://developers.google.com/assistant/conversational/webhook/reference/rest/Shared.Types/AppRequest#surface
```cs
var request = turnContext.GoogleGetSurfaceCapabilities();
```

Also, if you needed it, this one will get you the full request.
```cs
var request = turnContext.GetGoogleRequestPayload();
```

Hope that helps - sorry for the delay in coming back to you!

**Comment by arafattehsin** [comment]
Hi @aishwaryaumachandran - I hope you'll be able to implement the logic as per your requirement now. 🥇 Please re-open this issue if you encounter any bug. Closing this one for now!
