### ISSUE TITLE
[TwitterAdapter] [Feature-Request] Middlewares - Payload - Attachment - Buttons

### ISSUE THREAD

**Issue by marcasmar94** [BotBuilderCommunity/botbuilder-community-dotnet#202]
Is anyone working on these features in the Twitter Adapter ?

- Support for Middlewares
- Support for Quick Reply **metadata**
Metadata that will be sent back in the webhook request 
- Support for Media Attachment
Images, GIFs, video
- Support for Buttons (CTAs)

**Comment by garypretty** [comment]
Closing. This will be handled as part of #301
