### ISSUE TITLE
Adding community samples?

### ISSUE THREAD

**Issue by cleemullins** [BotBuilderCommunity/botbuilder-community-dotnet#22]
Hello BotBuilderCommunity!

We're starting to see samples - good ones! - being authored by the community. For example @rbrogan-git has ported the echobot sample to F#. 

What's the groupthink on using the BotBuilderCommunity as a landing zone for community projects & 
samples like this? It seems there are two good options:
1. Centralize the samples + extensions, so they're easy to discover. BotBuilderCommunity seems great for that. 
2. Decentralize the samples + extensions and encourage people to host everything in their own repo. This model seems a bit more "standard" in the github world, but does make discovery more difficult. 

Another options may be a variation on #2, where the product team (or this community) uses a particular Badge/Shield that people use:  
![BotBuilder](https://img.shields.io/badge/BotBuilder-Bottastic!-green.svg)

//Chris

**Comment by garypretty** [comment]
@cleemullins Thanks for raising this Chris - I do like the idea of hosting great community samples here.  I've been thinking about the fact recently that it would also be good to have samples for the various components we have within this repo too so that we can show usage.

I guess the question comes (which I know you have tackled previously) as to how to structure this.

I think my thoughts would be;

 - Within each of the current repos (i.e. dotnet, JS etc) we have a samples folder, which contains samples that directly relate to the components within the repo to show usage.

 - We could then create a separate repo botbuilder-community-samples which contains a folder for each language for broader samples - similar to the approach taken by the Product team with their separate samples repo. There is an argument to forget the first point and just go with the dedicated repo which houses everything.

Thoughts?

**Comment by cleemullins** [comment]
The biggest pros/cons I've seen so far is that automated builds & github branch protections is easier to setup if the repo is just one platform. 

For example, mixing C# and JS in a single repo makes doing CI difficult as the builds tend to be different.  If you have different builds, then they both get triggered on each commit. That in turn makes the branch protection rules in github ineffective, as there are no conditionals in there. 

I *suspect* if I were a better build engineer, I could work around this - but for now it's been causing me grief. 

Your call. For us, we optimized around what we thought our developers would find easiest:
1. Samples all in one repo
2. (v4) Each SDK in a dedicated repo
3. Tools are all in one repo

//Chris

**Comment by garypretty** [comment]
@cleemullins great point. I hadn't even considered that and I have enough trouble keeping on top of the CI for one platform! I'll have a think - but the more I think about it, the more I like the idea of having the usage samples directly related to the repo in the same place - its just a question of where to put the broader samples.

@szul @jamesemann @arafattehsin @cloudguy-pro feel free to chip in here.

**Comment by szul** [comment]
I think by putting the samples in the individual repos that they are related to at least keeps us aligned with the Bot Framework team's repos.

**Comment by cloudguy-pro** [comment]
I‘m with you both I think having a samples folder next to the middleware, dialogs and recognizers folders would be a good point to bundle samples for each language! And we could give the community a place to share cool samples as well for their language of choice...

**Comment by arafattehsin** [comment]
I think it's good to have relevant samples in the same repo, this would ease our build process as @cleemullins mentioned. Also, it will be easier for developers to find the working examples. 

For broader samples like Product team, we can follow the similar *folder* approach which they are following as well.

**Comment by garypretty** [comment]
Ok, I think we have agreement for now. Samples for each repo within the repo.  Ill be creating a samples folder alongside the libraries folder for the .NET repo in the next few days.  Got some good stuff to release next week and will need a sample to go with it.

**Comment by rbrogan-git** [comment]
Let me know where I should do the pull request for my F# sample.  Thanks!

**Comment by garypretty** [comment]
Hey everyone. I have added the first couple of samples for the dotnet repo in a samples folder.  There is a samples .sln file at the top level where new sample projects should be added to - this will allow me to setup CI for the samples at some point.

@rbrogan-git do you want to do ahead and add your sample to this repo?

**Comment by rbrogan-git** [comment]
Yes, that would be great!  How do you want me to structure the folders?  Since this is F#, should I start with an "fsharp" folder or put the language in the name of the project folder?  Want to make it easy to see what language is used since the other samples are in C#. 
Thoughts?

**Comment by garypretty** [comment]
Closing this as I think we have an agreed approach in practice now, with samples living in the repo they belong to. Thanks.
