### ISSUE TITLE
4.8.* nuget package seems to have no assembly reference to AlexaIntentToMessage Middleware

### ISSUE THREAD

**Issue by JaredLLewis** [BotBuilderCommunity/botbuilder-community-dotnet#248]
Hello,

I am trying to upgrade the Bot.Builder.Community.Adapters.Alexa DLL in my project from 4.5.3 to 4.8.5. I followed the Echo bot sample but I am unable to add the middleware to the adapter using this code:

`Adapter.Use(new AlexaIntentRequestToMessageActivityMiddleware());`

I am writing the following using statement

`using Bot.Builder.Community.Adapters.Alexa.Middleware;` 

This reference does not exist and I'm not sure where to find it. If anyone knows where this DLL or where the code is at for the middleware I would greatly appreciate it. I believe this is the issue why when I use the built in core methods AlexaSessionAttributes() always returns null, which means I can't add any values to its dictionary, and AlexaSetRepromptSpeech doesn't add the reprompt json to the alexa response. Any help would be appreciated, thank you!

**Comment by garypretty** [comment]
HI @JaredLLewis - the Alexa adapter has recently undergone some significant refactoring and the job the middleware used to carry out is now handled directly by the adapter itself, so you no longer need it.  Activities will automatically be transformed for you and you can see more details about the transform here https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Adapters.Alexa#incoming-alexa-request-to-bot-framework-activity-mapping

We also altered the reprompt functionality to automatically set the re-prompt value for you.

If you are still facing issues, I would really like to work with you to understand what you are seeing to help resolve the issue and figure out if we need to make some changes,

Finally, it looks like the session attributes functionality was dropped. I am curious what you were using this for that you couldn't use normal conversation state for?  Depending on your scenario, we might be able to add this back in to the adapter.

**Comment by NickEricson** [comment]
@JaredLLewis Have you had a chance to try what @garypretty suggests?

**Comment by JaredLLewis** [comment]
Hey guys. Thanks much for the reply. I was using the alexa session attributes because I didn't realize it automatically transformed the session attributes from the state management. My only question now is how can I set a custom re-prompt message? Is this possible?

**Comment by garypretty** [comment]
HI @JaredLLewis - it is no longer possible to set a custom re-prompt message, as we automatically set it for you (using the original text content) if you are expecting further input from the user.  If this is a problem, I would be interested to know more about your scenario so we can understand if there is anything we can do.

**Comment by NickEricson** [comment]
Hi @JaredLLewis  - I know it hasn't been long but just checking in. Does what @garypretty mentioned work for you?

**Comment by NickEricson** [comment]
Hi @JaredLLewis - I am going to close this out. Please re-open if you are still experiencing this or are interested in a change in functionality.
