### ISSUE TITLE
GoogleAdapter: Access to user information via response?

### ISSUE THREAD

**Issue by twardpragmaticworks** [BotBuilderCommunity/botbuilder-community-dotnet#260]
The Alexa adapter offers the below function to access personal data stored on the device.  Does the Google adapter offer anything similar?

````
  // you can also use the available context extension to get the SkillRequest object - context.GetAlexaRequestBody();
    var profileClient = new CustomerProfileClient((SkillRequest)stepContext.Context.Activity.ChannelData);
    var profileAddress =  await profileClient.FullAddress();
    var profileAddressLine1 = profileClient.FullAddress().Result.AddressLine1;

````

**Comment by garypretty** [comment]
Hi.

You can obtain the users Name (display / given / family name), coarse location (zip code / city) or precise location (coordinates / street address) by using the Permissions intent (you can read more about the intent here -> https://developers.google.com/assistant/conversational/helpers#user_information).

When you send the Permissions intent (as an attachment on your outgoing activity), if the user grants the permissions you asked for, then the information you requested will be received on an Event activity received by your bot.

Here is a quick example of how you should be able to approach this.

**Sending the activity **

```cs
var activity = MessageFactory.Text($"Ok, I need your permission.");

var permissionsIntent = new PermissionsIntent() {
    InputValueData = new PermissionsInputValueData()
};
permissionsIntent.InputValueData.Permissions.Add(Permission.NAME);
permissionsIntent.InputValueData.Permissions.Add(Permission.DEVICE_PRECISE_LOCATION);

activity.Attachments.Add(permissionsIntent.ToAttachment());
await turnContext.SendActivityAsync(activity, cancellationToken);
```

Then you can look for the incoming event activity using OnEventActivityAsync on your activity handler.  When you receive the activity, the data you have been granted will be on the ChannelData object on the incoming activity.

```cs
protected override async Task OnEventActivityAsync(ITurnContext<IEventActivity> turnContext, CancellationToken cancellationToken)
        {
.......
        }
```

Hope that helps.

**Comment by garypretty** [comment]
I'm going to close this out now, let me know if the above doesn't help.
