### ISSUE TITLE
Link to the WhatsApp adapter leads to a 404

### ISSUE THREAD

**Issue by samaea** [BotBuilderCommunity/botbuilder-community-dotnet#261]
The link on the repro's homepage for the "InfoBip WhatsApp Adapter" hyperlink leads to a 404 page. I believe it should link to https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/master/libraries/Bot.Builder.Community.Adapters.Infobip.

**Comment by NickEricson** [comment]
@samaea Thank you for reporting this. We have fixed the link.
