### ISSUE TITLE
LocationDialog. Incorrect flow of dialog

### ISSUE THREAD

**Issue by Unders0n** [BotBuilderCommunity/botbuilder-community-dotnet#27]
Hi, thanks for component, though i have an issue. All flow is working well, all asking of address, showing images, confirmation, but when i hit "Yes" in confirmation second step of waterfall doesn't hit, when i type smth more, it hits but WaterfallStepContext.Result is null and WaterfallStepContext.Reson is "EndCalled"
![image](https://user-images.githubusercontent.com/18035628/49143021-270aa900-f30b-11e8-95de-42aba125155a.png)

here's the code:
` ...
          //location
            AddDialog(new LocationDialog("eSXXarWY1t6T2MQS-Ibdc2lqbZ42kWvYNADhiVpFMmk",
                "Please enter a location",
                _userState,
                useAzureMaps: true,
                requiredFields: LocationRequiredFields.PostalCode,
                options: LocationOptions.SkipFavorites 
            ));

            AddDialog(new WaterfallDialog("LocationFullDialog", new WaterfallStep[]
            {
                BeginLocationCollectDialog,
                OnCollectLocationDialog
            }));

        }

        private async Task<DialogTurnResult> OnCollectLocationDialog(WaterfallStepContext dc, CancellationToken cancellationToken)
        {
            if (dc.Result is Place returnedPlace)
            {
                await dc.Context.SendActivityAsync($"Location found: {returnedPlace.Address.ToString()}");
            }
            else
            {
                await dc.Context.SendActivityAsync($"No location found");
            }

            return await dc.EndDialogAsync();
        }

        private async Task<DialogTurnResult> BeginLocationCollectDialog(WaterfallStepContext dc, CancellationToken cancellationToken)
        {
            return await dc.BeginDialogAsync(LocationDialog.DefaultLocationDialogId, cancellationToken);
        }

        public async Task<DialogTurnResult> AskForPhone(WaterfallStepContext sc, CancellationToken cancellationToken)
        {
            return await sc.BeginDialogAsync("LocationFullDialog", cancellationToken);
 `

This is tjus another dialog that is also started from main dialog by BeginDialogAsync

NetCore app 2.1
AspNetCore.App 2.1.6
BotBuilder 4.1.5
Dialogs.Location 1.0.100

**Comment by garypretty** [comment]
@Unders0n Hi, thanks for raising this. I think I found the same problem a few days ago and do have a fix for this.  I am stacked at the moment, so it will be a few days, but I will get it pushed here ASAP.

**Comment by Unders0n** [comment]
@garypretty thx for rapid response. So it was working correctly, right, so smth changed in flows of dialogs in botbuilder framework?

**Comment by Unders0n** [comment]
btw i mentioned that you're using "dc.Context.SendActivity" in your samples, but its not there not, just dc.Context.SendActivityAsync, so my guess that you're using another version of botbuilder.

**Comment by garypretty** [comment]
@Unders0n Hi.  New version published to NuGet just now. 👍  Will close this, just re-open if you still have the issue.

**Comment by Unders0n** [comment]
Thanks! It worked for me. But now i faced issues in web chat control, do you know if this aproach should work in web chat control using directline (https://cdn.botframework.com/botframework-webchat/latest/botchat.css) ?  Have such error logs in appinsights: 
![image](https://user-images.githubusercontent.com/18035628/49341177-cbb61f00-f65a-11e8-853b-47a6d6fe6a6b.png)

**Comment by Unders0n** [comment]
Hi, Any updates?
