### ISSUE TITLE
Adapter doesn't works when a request is ConnectSkill type

### ISSUE THREAD

**Issue by guilhermecaixeta** [BotBuilderCommunity/botbuilder-community-dotnet#272]
Currently I've been trying make a skill connection between two alexas skills, but the provider skill is a type of bridge to the Botframework skill.  

If I call the skill directly works well, but if I try call it by a connection skill directive an error is throw in the serialization of request.

The message is: `unable to deserialize response. unrecognized task type '' with version ''`

Alexa.Adapter version: 4.8.7
Microsoft.BotBuilder.* version: 4.9.2

**Comment by NickEricson** [comment]
@guilhermecaixeta any chance you have the call stack and the specific message you are sending from your bot/alexa?

**Comment by guilhermecaixeta** [comment]
@NickEricson sorry for my late, as soon as possible I'll update this issue with the call stack. Thank you for your availability.

**Comment by guilhermecaixeta** [comment]
I would like to say sorry, I've been have some troubles because I'm use the skill of adapter as a skill connection, but to do this is needed to apply some requirements and now I don't have more access to the skill, but the error that I have it's referred to serialization of the Alexa request, this is the example of [request](https://developer.amazon.com/en-US/docs/alexa/custom-skills/implement-amazon-predefined-tasks-in-your-skill.html#example-task-request).

I used this documentation to make a [skill connection](https://developer.amazon.com/en-US/docs/alexa/custom-skills/use-skill-connections-to-request-tasks.html).

**Comment by NickEricson** [comment]
@guilhermecaixeta No problem and thanks for following up.

I tried the request you mentioned (the launch - print pdf request) and, unfortunately I didn't get the error you are seeing. There could be a property that I'm setting that isn't set for you.

If you would like to keep looking into this let me know - otherwise I can close it out.

Here is what I sent through the adapter:

{
  "version": null,
  "session": {
    "new": false,
    "sessionId": null,
    "attributes": null,
    "application": null,
    "user": {
      "userId": null,
      "accessToken": null,
      "permissions": null
    }
  },
  "context": {
    "System": {
      "apiAccessToken": null,
      "apiEndpoint": null,
      "application": {
        "applicationId": null
      },
      "user": {
        "userId": null,
        "accessToken": null,
        "permissions": null
      },
      "device": null
    },
    "AudioPlayer": null,
    "Geolocation": null
  },
  **"request": {
    "task": {
      "name": "AMAZON.PrintPDF",
      "version": "1",
      "input": {
        "@type": "PrintPDFRequest",
        "@version": "1",
        "title": "Flywheel",
        "description": "Flywheel",
        "url": "http://www.example.com/flywheel.pdf"
      }
    },
    "type": "LaunchRequest",
    "requestId": "amzn1.echo-api.request.00000000-0000-0000-0000-000000000000",
    "locale": "en-US",
    "timestamp": "2020-07-02T17:29:12.9822758-07:00"
  }**
}

The bolded section is the PrintPDF request.

If you can capture the exact Json you are getting from Alexa I'd be happy to run it through to see what I get.

**Comment by guilhermecaixeta** [comment]
In a few words my problem occurs when the conversion occurs, I can achieve the Microsoft bot code. But I'll try see how I could simulate again and share the code here, sorry about that.

**Comment by garypretty** [comment]
Closing this issue out for now, but if you are able to share more details please re-open.
