### ISSUE TITLE
Alexa rarely reading choices in choiceprompt 

### ISSUE THREAD

**Issue by AndyfromPBG** [BotBuilderCommunity/botbuilder-community-dotnet#273]
I started with the echo bot and customized to my scenario, but I've found that my choice prompts (via a waterfall sub dialog of the main dialog) often don't get read. They will rarely- I'd say once out of twenty times or so, and I can't find a pattern. I hate to just throw up my hands and say it's a bug and not my fault, but I don't see much I could be doing wrong. I'd be glad to do some legwork if someone would be nice enough to point me in the right area, and perhaps I could fix it myself. I know these choices work, because they show up in text chats, and I've tried every list style that there is but None.

`        private async Task<DialogTurnResult> ServiceStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
        {
            ...
                    var promptMessage = MessageFactory.Text(ServiceStepMsgText, ServiceStepMsgText, InputHints.ExpectingInput);
                    var retryPromptMessage = MessageFactory.Text(RetryChoiceStepMsgText, RetryChoiceStepMsgText, InputHints.ExpectingInput);
                    List<Choice> choices = organization.Services.Select(s => new Choice(s.Name) { /*Synonyms = "", Action = new CardAction*/ }).ToList();
                    return await stepContext.PromptAsync(nameof(ChoicePrompt), new PromptOptions
                    {
                        Prompt = promptMessage,
                        RetryPrompt = retryPromptMessage,
                        Choices = choices,
                        Style = ListStyle.SuggestedAction
                    }, cancellationToken);
                }
            }

            return await stepContext.NextAsync(appointmentDetails.Service, cancellationToken);
        }
`

**Comment by NickEricson** [comment]
@AndyfromPBG The conversion from Activities to an Alexa Response is done in two steps:

1) Merge Activities into a single activity: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/144427091d2ad5315e00fe67228f3ad804463f62/libraries/Bot.Builder.Community.Adapters.Alexa.Core/AlexaRequestMapper.cs#L137
2) Convert the Activity to an Alexa Response: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/144427091d2ad5315e00fe67228f3ad804463f62/libraries/Bot.Builder.Community.Adapters.Alexa.Core/AlexaRequestMapper.cs#L78

It could be the 1st one not copying the choices to the final activity. If you have the activities sent from your bot in working and non-working cases send them to me at nericson @ microsoft.com (remove any personal information please) or you can take a look at the code I linked.

**Comment by AndyfromPBG** [comment]
@NickEricson Thanks so much, I bet this will be enough to get me going but I'll either post when I figure out what I did wrong or send you more details.

**Comment by AndyfromPBG** [comment]
I feel beyond stupid- all I had to do was not supply a SSML text value, and then the regular text value, read aloud with all the choices, came through the speaker. I'm guessing that the SSML value overrides whatever the text value ends up as, so just not specifying it was the way to go. Closed, thanks!
