### ISSUE TITLE
Alexa - locale not populated on launch requests

### ISSUE THREAD

**Issue by jamesemann** [BotBuilderCommunity/botbuilder-community-dotnet#277]
#### Background

We've upgraded to 4.9 and spotted an edge case which I think is a bug in the new Alexa adapter.  Some of our customers use auto translation which uses the `activity.Locale` field on the launch message.  This used to be mapped on all requests but now it is only mapped where it an intent is triggered (see [this line](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Alexa.Core/AlexaRequestMapper.cs#L188)).

In the Alexa request you can see here is the locale - so mapping this value on launch makes sense:

![image](https://user-images.githubusercontent.com/6830648/85031648-d79efe80-b176-11ea-801b-f2964a135fc9.png)

#### Proposal
I think the fix is as simple as moving the mapping to the `SetGeneralActivityProperties` so that it always maps this value on all requests if available.

@garypretty can you take a look at my thinking and confirm or not. If correct I can go ahead and put in a PR for it.  I'll be putting this in today at Zammo and testing so I can update this issue with test results from that, but wanted to give you a heads up on it.

**Comment by garypretty** [comment]
Hi @jamesemann. I think your proposal makes sense, so please do go ahead and raise a PR. Thanks.

**Comment by jamesemann** [comment]
Hello, hello @garypretty. I've put in a PR 281 mentioned above for this.

**Comment by garypretty** [comment]
PR #281 merged and will be included in next release. Planned for early / mid this week.
