### ISSUE TITLE
Adding Dialog Prompts

### ISSUE THREAD

**Issue by rvinothrajendran** [BotBuilderCommunity/botbuilder-community-dotnet#278]
Add all the missing prompts in dot net 
1.	Email
2.	Phone number
3.	IP address
4.	Social Media
5.	Internet 

@garypretty will create a PR ?

**Comment by garypretty** [comment]
@rvinothrajendran i haven't got capacity to pick this up at the moment. Let's label it as needs help and see if anybody else can assist.

**Comment by rvinothrajendran** [comment]
@garypretty Will I take ?

**Comment by garypretty** [comment]
@rvinothrajendran if you have capacity then great.
