### ISSUE TITLE
Form appears to destroy the dialog stack

### ISSUE THREAD

**Issue by Rufus1123** [BotBuilderCommunity/botbuilder-community-dotnet#279]
We have SubDialog in MainDialog, and within the SubDialog, we have a WaterfallDialog. In the FirstStep of WaterfallDialog we call the Form like this:
```
return await stepContext.BeginDialogAsync(nameof(TheForm), cancellationToken: cancellationToken);
```
We can successfully go through the form, however, when we start a SubSubDialog from within the SecondStep of the SubDialog, things seem broken.

The SecondStepExecutes and starts the SubSubDialog. There we have another WaterfallDialog the in the FirstStep prompts the user for input:
```            
return await stepContext.PromptAsync(nameof(SubSubDialogPrompt), new PromptOptions()
            {
                Prompt = MessageFactory.Text("Do you want to go to step 2?"),
            }, cancellationToken);
```
However, SecondStep of SubSubDialog never executes.
After replying to the prompt, we can inspect the activity that has been sent in the `OnContinueDialogAsync` method of MainDialog. At that point, the `innerDc.Parent` is already the MainDialog, and not the SubSubDialog which it should be.

If we replace the BeginDialog of TheForm by simply going to the next step (`return await stepContext.NextAsync()`) everything works as expected.

**Note**:
We started with [the virtual assistant](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/2-download-and-install/). A key difference with the samples here is the way dialogs are managed. We have `return _dialog.RunAsync(turnContext, _dialogStateAccessor, cancellationToken);` in the `OnMessageAsync` method of the `ActivityHandler`, whereas the sample uses the `OnTurnAsync` method, creates the context manually and BeginDialog/ContinueDialog from there.

**Comment by devedse** [comment]
@EricDahlvang , Hi Eric, both me and Rufus1123 are working on this issue. We're both available to contact directly through teams if that's the communication system you prefer. Gary should have both of our email addresses :).

**Comment by EricDahlvang** [comment]
@devedse Thanks, I spent some time looking at this yesterday. I'll ping you two on Teams.

**Comment by EricDahlvang** [comment]
There are definitely issues using Waterfall Dialogs with FormFlow.  Until we can get a fix released, the recommendation is to not use FormFlow within a Waterfall Dialog.

**Comment by mrivera-ms** [comment]
@garypretty, after an offline conversation with Eric, the recommendation is to close this item. Can you comment?

**Comment by garypretty** [comment]
Closing.
