### ISSUE TITLE
Botbuilder community Adaptive dialog supported input

### ISSUE THREAD

**Issue by rvinothrajendran** [BotBuilderCommunity/botbuilder-community-dotnet#308]
Convert Bot.Builder.Community.Dialogs.Prompts to Adaptive dialog supported prompt.

@garypretty 
I have tried EmailPrompt to Adaptive dialog EmailInput & Its working fine.
what's your idea? Will continue on this.

**Comment by garypretty** [comment]
I think we should discuss this. I think we will want to have a section where we share Custom Actions for Composer, which this could form part of.

**Comment by rvinothrajendran** [comment]
@garypretty Yes , I can able to wrap into Custom Action ( Sorry for late reply busy with project work)


**Input form**

![image](https://user-images.githubusercontent.com/16264167/100496043-22bf3380-3151-11eb-996e-6225005acf0e.png)

**test in emulator** 
![image](https://user-images.githubusercontent.com/16264167/100496051-336fa980-3151-11eb-9bfe-0a6f21281b1c.png)

**Comment by rvinothrajendran** [comment]
@garypretty 
stuck up with two areas
1.Not yet started the unit testing, so far, no documents are available to write the unit testing for adaptive dialog (is in preview)
2.Deployment of schemas file
Can you share your idea on this?

**Comment by garypretty** [comment]
@rvinothrajendran I think we should hold here for a couple of weeks.  We are landing on the list of packages for Composer that will be made available from the core team and then we will know where the gaps will be.  I then suggest we deliver the above as Composer packages.

**Comment by rvinothrajendran** [comment]
started rest of prompts to input

**Comment by rvinothrajendran** [comment]
@garypretty  I sent mail to you. Kindly share your feedback.

CustomInput 

![image](https://user-images.githubusercontent.com/16264167/112525692-6cd3c100-8da1-11eb-8328-9f5afa9d9fd6.png)



SocialMediaType Input

![image](https://user-images.githubusercontent.com/16264167/112525275-0353b280-8da1-11eb-90b8-56ecd6a1a89e.png)


PhoneNumber Input

![image](https://user-images.githubusercontent.com/16264167/112525387-21211780-8da1-11eb-8e6c-18ddd206cde5.png)

**Comment by garypretty** [comment]
Closing as inputs now merged - thanks @rvinothrajendran!

**Comment by rvinothrajendran** [comment]
Thanks   @garypretty , I will add missing input types later next week.
