### ISSUE TITLE
Translation Samples needs to translate Hero Cards and multiple input choice action

### ISSUE THREAD

**Issue by madbeher** [BotBuilderCommunity/botbuilder-community-dotnet#324]
Hi,

Below sample is working for normal text messages 

https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/17.multilingual-bot

But translation, where cards (hero and multiple input choice action) are not being translated.

Consider updating this sample to include an hero and multiple input choice action  translation.

Thanks...

**Comment by ismendes** [comment]
Here's an example of what's happening:
![image](https://user-images.githubusercontent.com/56369624/94745263-36a41000-032f-11eb-9570-4307934002cc.png)
@madbeher, can you add more images of other points where the translation doesn't work? This is a big step for us in the Partner Bot, and the more help we can provide the Bot Framework community, faster they will be able to understand the problem and guide/help.

**Comment by garypretty** [comment]
Hi. Thank you for the issue. The sample you are referring to is actually part of the Microsoft samples repo and not the Community project.  I would suggest you raise this issue within the official Bot Builder Samples repo at https://github.com/microsoft/BotBuilder-Samples where the engineers can look at your request.
