### ISSUE TITLE
How to create continuous conversation based on certain topic / context for Google adapter ?

### ISSUE THREAD

**Issue by gitguy007** [BotBuilderCommunity/botbuilder-community-dotnet#325]
Hi, first of all ..  thanks for all the good work that has been put into this adapter. It is amazing 👍 

I am trying to create a simple game that will be triggered by a keyword and there will be continuous messages as the Google Assistant will ask the user.

For example, user keys in "Knock knock" and the Google Asst will reply "Who is there" and so on ..

Every time the user replies, Google Asst will provide a reply. The conversation flow will be based on this game and only after user saying "Goodbye" will end it.

May I know what is the best way to achieve this continuous flow using this adapter ? i.e. via Intents or detecting the messages in the source code  itself ?

**Comment by arafattehsin** [comment]
Hi @gitguy007 Thank you for this. May I know if your conversation flow is sequential?

**Comment by gitguy007** [comment]
Hi thanks for your quick reply. Yes, it is sequential.

**Comment by arafattehsin** [comment]
@gitguy007 Cool then! Have you explored the [Waterfall Dialog sample](https://github.com/Microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/05.multi-turn-prompt) from the Bot Builder Samples repo? If not then I think this should resolve your issue. 

Please let me know if it does not fulfill your requirements.

**Comment by gitguy007** [comment]
Noted. 

I thought that the botbuilder-dialogs is independent from the Google adapter class .. will give this a try to see if this can be supported within the Google dialog flow.

**Comment by arafattehsin** [comment]
@gitguy007 If you're using DialogFlow just to send you what ever is coming from Google Assistant then I think this should be fine. I will also try to do the same myself if I get time this week and will let you know!

**Comment by gitguy007** [comment]
@arafattehsin,  i will do the same as well.

Thanks and have a great week :)

**Comment by arafattehsin** [comment]
Hi @gitguy007 - I tried with the Waterfall and it worked like a charm. I'm closing this issue now. Please re-open if you think anything related to Google / Action Custom Adapter is not working.

**Comment by gitguy007** [comment]
@arafattehsin, thanks for letting me know. I will reach out to you if i have any questions :)
