### ISSUE TITLE
twilio for whatsapp adapter

### ISSUE THREAD

**Issue by pomarc** [BotBuilderCommunity/botbuilder-community-dotnet#336]
hello.
Is there any roadmap to implement a .net adapter for twilio Whatsapp, as done for JS?(https://www.npmjs.com/package/@botbuildercommunity/adapter-twilio-whatsapp#advanced) 
thanks.

**Comment by Silu321** [comment]
Connect **Azure Bot** With **what's App** through **infobip** recommended Language is **C#** .can you plz.......... help me

**Comment by arafattehsin** [comment]
@Silu321 I am sorry but I had to remove your comment as you've already raised the issue.

**Comment by garypretty** [comment]
Currently we have no plans to implement a .NET version of this adapter.  Community contributions are of course welcome.  There is an adapter for InfoBip and a MessageBird adapter also in PR for WhatsApp.

**Comment by ahmetkocadogan** [comment]
@pomarc MessageBird WhatsApp adapter is released now. 
https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Adapters.MessageBird

NuGet : https://www.nuget.org/packages/Bot.Builder.Community.Adapters.MessageBird/

I also have a sample project in PR now, https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/pull/333

I can help if you have an issue with MessageBird. Just raise an issue.
