### ISSUE TITLE
Does Alexa Adapter support multi turn converstation

### ISSUE THREAD

**Issue by sivaelango-r** [BotBuilderCommunity/botbuilder-community-dotnet#337]
HI,

I am implementing a skill where alexa would need to converse multiple times to find what a user needs from using the skill.

For Eg:

User: ask test bot to plot histogram of brent
alexa: do you have a date range in mind
User: yes
alexa: give me the start and end date range
User: Jan 1st 2020 to Oct 1st 2020

Does alexa adapter support this multi turn conversation?

**Comment by arafattehsin** [comment]
Hi @sivaelango-r - yes, the multi-turn conversation is supported through ShouldEndSessionByDefault property. 

However, as per your above use-case, I'd recommend you to use the out of the box Alexa channel which comes with Azure Bot Service. 

I hope it answers your question.

**Comment by sivaelango-r** [comment]
Hi

Thanks for the response.
Yes the Azure bot currently uses the Alexa channel.   

Does the Alexa adapter support 
https://developer.amazon.com/en-US/docs/alexa/custom-skills/dialog-interface-reference.html

Just as it currently supports
https://developer.amazon.com/en-US/docs/alexa/custom-skills/display-interface-reference.html
using DisplayRenderTemplateDirective

**Comment by garypretty** [comment]
No we don't currently have support for that within the adapter.  For any functionality like that we would usually recommend using native Bot Framework capabilities on the Alexa channel.

Regarding the multi turn conversation, as well as setting ShouldEndSessionByDefault, you can also use the InputHint property on the outgoing activity. Setting this to IgnoringInput means no further input, setting it to ExpectingInput will expect more from the user.

**Comment by arafattehsin** [comment]
Thanks @garypretty. 

Closing this now. @sivaelango-r, please re-open in case your issue does not get resolved by setting ShouldEndSessionByDefault as explained above.
