### ISSUE TITLE
Zoom adapter: OAuthPrompt.Recognize(): not supported by the current zoom adapter

### ISSUE THREAD

**Issue by SonOfJesseAsSnekithan** [BotBuilderCommunity/botbuilder-community-dotnet#339]
I am trying to use the existing bot code with Zoom adapter, where OAuthPrompt::BeginDialogAsync  throws exception saying OAuthPrompt.Recognize() not supported by the current adapter.
 Is OAuthPrompt dialog is not supported in Zoom adapter?
Any feedback is appreciated.

**Comment by garypretty** [comment]
No, this dialog is not supported within the adapter. The prompt is designed to work with Azure Bot Service and since this is an adapter, it won't work currently.

**Comment by SonOfJesseAsSnekithan** [comment]
What is the work around solution here?, I need to get an access token for the user, so that bot can perform on behalf of the user.

**Comment by SonOfJesseAsSnekithan** [comment]
Yes, I agree, currently OAuthPrompt dialog checks whether adapter implements IExtendedUserTokenProvider interface, currently it is not, so it return error. I would like to provide some work around solution such as having a SignInCard and clicking sign-in button could launch the OAuth flow.  OAuthPrompt dialog implements automatic sign-in flow and 'magic-code' flow,  which falls into what kind of the OAuth flow  as in here (https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#authorization-code). Any feedback is appreciated. Thanks
