### ISSUE TITLE
MessageBird WhatsApp Adapter Nuget descriptions are missing

### ISSUE THREAD

**Issue by ahmetkocadogan** [BotBuilderCommunity/botbuilder-community-dotnet#343]
Description of Bot.Builder.Community.Adapters.MessageBird nuget package is missing. We should update that. 

Is there a way for me to update ?

![image](https://user-images.githubusercontent.com/7287309/99362298-5d5cdc80-28c4-11eb-8160-4e97a553325a.png)

**Comment by garypretty** [comment]
@ahmetkocadogan yes, you can set within the csproj file - take a look at the Alexa / Google adapters
