### ISSUE TITLE
Unable to find Nuget Package "Bot.Builder.Community.Cards"

### ISSUE THREAD

**Issue by Aavi2105** [BotBuilderCommunity/botbuilder-community-dotnet#352]
Hi @v-kydela  :- I have a requirement to disable adaptive card button and was referring this readme  "https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/feature/cards/libraries/Bot.Builder.Community.Cards/README.md" to try out steps in my code. I am unable to find this Nuget package "Bot.Builder.Community.Cards" while trying installing in VS 2019. Can you please suggest how to install that? 
Also, When I was referring Card library Samples solution for above, I am unable to find "Bot.Builder.Community.Cards" assembly in that solution.  Please suggest how I can try out running this code in my local system.

![image](https://user-images.githubusercontent.com/68352642/102739834-d1e7c880-4313-11eb-9c12-c3516d0315a3.png)

Thanks
Aavi

**Comment by v-kydela** [comment]
@Aavi2105 - Thank you for your interest in the cards library, and sorry you're having trouble with it! In the meantime, you can rely on the source code from GitHub directly. In order to run the sample, it will need to be connected to the local cards library project instead of NuGet.

@garypretty - Please look into why the cards library is not in NuGet

**Comment by Aavi2105** [comment]
Hi @v-kydela :- I don't see project file while going to library folder using add project reference from sample solution. Please suggest if I am missing something over here. 

![image](https://user-images.githubusercontent.com/68352642/102845137-7d575280-43d2-11eb-8034-46ff0c4e800e.png)

![image](https://user-images.githubusercontent.com/68352642/102844941-176acb00-43d2-11eb-9127-c76e77964c0c.png)

Note, Just to give you an idea, We have built Chabot solution using Power Virtual Agent and Azure Bot Skill action where using Azure skill bot we are rendering adaptive card back to PVA and displaying to User on D365 Omni channel Customer Chat Widget.  As part of this solution, when user click adaptive card menu , bot sends that as an activity to method "OnContinueDialogAsync" in MainDialog class. I believe for disabling other menus , I need to write piece of code inside "OnContinueDialogAsync" method only?  For that I want to first debug your sample code to get an idea on sequence of steps to be followed for disabling buttons and need your help on getting me sample solution running in my local.

Thanks
Aavi

**Comment by v-kydela** [comment]
The project file is right here: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Cards/Bot.Builder.Community.Cards.csproj

If you are missing files, then it might be a good idea to clone the repo again

**Comment by Aavi2105** [comment]
Hi @v-kydela - I am able to see project file when I go to the card library project folder directly, but unable to see the same when try adding via project reference mentioned in previous post. This time I tried another way of doing it, just added bot.builder.commnity.cards project directly inside the main sample solution (Bot.Builder.Community.Samples) and then tried adding the library card project file reference inside "cards library sample" project , but see yellow/warning symbol for library project as shown below. Can you please try following the same steps in your local and let me know if I am missing any steps.    

![image](https://user-images.githubusercontent.com/68352642/102930318-caced080-4461-11eb-9758-f357bf39508e.png)

**Comment by v-kydela** [comment]
Oh I think I see now. You need to build the cards library first, and then add Bot.Builder.Community.Cards.dll as the reference, not the .csproj file.

**Comment by Aavi2105** [comment]
Thanks @v-kydela , Yes it built now successfully. Question, I am able to run this sample solution locally using emulator after adding card library dll reference, but don't see buttons or card to be disabled/deleted in emulator chat window , does it work for for emulator ?

**Comment by v-kydela** [comment]
Yes, the sample works in Emulator

**Comment by Aavi2105** [comment]
HI @v-kydela :- I tried debugging above code and understand that card button is disabled after I get the result "Thank you for choosing {label}!" , but in a moment if user click same button twice or multiple button before response of first button appears then this throws same result twice how we can handle this scenario?

**Comment by Aavi2105** [comment]
Hi @v-kydela :- Since I am using  Dynamics 365 Omni channel Customer Chat to render adaptive cards from bot and I checked that Omnichannel chat treats this as msteams channel, hence I referred another of your blog (https://github.com/microsoft/botframework-sdk/issues/5472) where you suggested to use update activity event to replace old card with new card for a given conversation and for that I added below code snippet in my bot solution to update adaptive card with another card but I see that it get's into failure on update event when I render into Omnichannel chat widget. Please suggest if I am doing anything  wrong over here or update is not supported for D365 omnichannel. 

protected override async Task<DialogTurnResult> OnContinueDialogAsync(DialogContext innerDc, CancellationToken cancellationToken = default)
        {
            var activity = innerDc.Context.Activity;
            
            if (innerDc.ActiveDialog.State.ContainsKey("adaptivecardactivityid"))
            {
                object card = new AdaptiveCard("1.0")
                {
                    Body = new List<AdaptiveElement>
                {
                    new AdaptiveTextBlock
                    {
                        Text = "Cards library demo",
                        Size = AdaptiveTextSize.ExtraLarge,
                        Weight = AdaptiveTextWeight.Bolder,
                        Wrap = true,
                    },
                    new AdaptiveTextBlock
                    {
                        Text = "Adaptive Card translation",
                        Size = AdaptiveTextSize.Large,
                        Weight = AdaptiveTextWeight.Bolder,
                        Wrap = true,
                    },
                    new AdaptiveTextInput
                    {
                        Id = IdText,
                        Placeholder = "Text",
                    },
                    new AdaptiveNumberInput
                    {
                        Id = IdNumber,
                        Placeholder = "Number",
                    },
                    new AdaptiveDateInput
                    {
                        Id = IdDate,
                        Placeholder = "Date",
                    },
                    new AdaptiveTextBlock
                    {
                        Text = "Fill in the inputs and then click a button to see if the values are preserved."
                                + " (This demo only applies to Microsoft Teams)",
                        Wrap = true,
                    },
                },
                    Actions = new List<AdaptiveAction>
                {
                    new AdaptiveSubmitAction
                    {
                        Title = "Submit normally",
                        Data = new
                        {
                            behavior = BehaviorSubmit,
                        },
                    },
                    new AdaptiveSubmitAction
                    {
                        Title = "Submit and preserve",
                        Data = new
                        {
                            behavior = BehaviorPreserve,
                        },
                    },
                },
                };

                var attachment = new Attachment()
                {
                    ContentType = AdaptiveCard.ContentType,
                    Content = card,
                };
                await innerDc.Context.SendActivityAsync(activity.ChannelId);  // I get this as msteams channel in omnichannl customer chat visit.
                var update = innerDc.Context.Activity.CreateReply(activity.Text);
                update.Attachments = new List<Attachment> { attachment };
                update.Id = innerDc.ActiveDialog.State["adaptivecardactivityid"].ToString();  
                await innerDc.Context.SendActivityAsync(innerDc.ActiveDialog.State["adaptivecardactivityid"].ToString()); // For Print
                await innerDc.Context.UpdateActivityAsync(update, cancellationToken);
                await innerDc.Context.SendActivityAsync("Update Successfully"); // For Print
                var actionResponse = new SampleActionOutput
                {
                    CustomerId = activity.Conversation.Id,
                    CustmerResponse = "ABC",
                    CustmerResponseId = "DummyId"
                    //val.selectedId

                };
                return await innerDc.EndDialogAsync(actionResponse, cancellationToken);

            }

           
            return await base.OnContinueDialogAsync(innerDc, cancellationToken);
        }

**Comment by v-kydela** [comment]
@Aavi2105 - I'm sorry, the cards library wasn't designed for D365 and I've never used it so I can't really say much on that topic. The cards library is meant to work on any channel so D365 should work but I don't know if it supports message updates or not.

**Comment by Aavi2105** [comment]
Thanks @v-kydela for your response. Do you suggest to check with D365 Omni channel team for the same if above code (update activity) snippet written in bot solution looks okay ?

**Comment by v-kydela** [comment]
@Aavi2105 - No, I suggest experimenting with the Bot Framework REST API to see if you can update activities in D365. If it truly uses the Teams channel then you should be able to.

**Comment by Aavi2105** [comment]
Hi @v-kydela  - After printing exception msg into Omni channel chat widget I found that below exception is thrown by bot when it tries to update / delete existing activity. Any clue/help on this ?

Operation returned an invalid status code 'NotImplemented'

**Comment by Aavi2105** [comment]
Hi @v-kydela :- I tried using bot framework delete rest api to check if delete works for existing activity id for the same live conversation. What I tried here , after getting first adaptive card message activity in Omni channel chat session , I put the session conversation id and adaptive card activity id into delete rest api and hit it from postman client and get below response 202, but I was still able to see old activity in Omnichannel chat  session. 

Do you see if I missed anything over here from delete rest api side?   
![image](https://user-images.githubusercontent.com/68352642/104509335-25fe6980-55af-11eb-8387-7db83e03e7ae.png)

**Comment by v-kydela** [comment]
@Aavi2105 - If you used the correct service URL and conversation ID and activity ID and bearer token then I can't think of anything you might have missed. It's possible that the Skype server processed the delete request successfully but the client just isn't designed to delete messages. Please keep in mind that I don't know what Omnichannel is so I'm not the right person to ask about that. I support the channels found in the [Bot Framework docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-channels#connect-a-bot-to-a-channel).

**Comment by Aavi2105** [comment]
Thanks @v-kydela  for your response, I was just checking if the api was correctly called and if you see any missing thing over there. 
Also, one more ask which I mentioned in previous questions, do you know what could be cause of getting below error message which I get when using updateactivity method from skill bot code. I am not getting much information online to find the exact root cause of this error message. 

Error Message : Operation returned an invalid status code 'NotImplemented'

**Comment by v-kydela** [comment]
@Aavi2105 - When a class implements an interface but doesn't provide an implementation for some of that interface's functions, it's common to throw a not-implemented exception as a sort of default implementation

**Comment by EricDahlvang** [comment]
Hi @Aavi2105 

Which version of the sdk is the bot using?   Update and Delete from a skill were introduced with the 4.11 release (from this PR: https://github.com/microsoft/botbuilder-dotnet/pull/4786 )

**Comment by Aavi2105** [comment]
Hi @EricDahlvang - Thanks for checking this, Yes I ensured that skill bot is referring latest nuget package with sdk version  4.11.1. 

Thanks
Aavi

**Comment by garypretty** [comment]
Sorry for the delay in jumping in here - I have resolved an issue with the build pipeline and the package is now available on NuGet at https://www.nuget.org/packages/Bot.Builder.Community.Cards/
