### ISSUE TITLE
Natural Conversation templates

### ISSUE THREAD

**Issue by sempjc** [BotBuilderCommunity/botbuilder-community-dotnet#354]
I would like to propose a project about a collection of *Natural Conversation Dialogs*. This idea is inspired on the works of Robert J. Moore and Raphael Arar from his book *Conversational UX Design: A Practitioner's Guide to the Natural Conversation Framework (AMC Books)*. Currently I applied a similar idea on my projects and I see the benefit of having dialogs ready to use. 

For example I have a bot for helpdesk support and I have created a TicketStatusRequestDialog, NewTicketDialog and use it on three different conversations. This conversations are about three different tickets type but all share the same dialogs pattern. This allow me to work with more consistency and efficiently. Also this let me delegate work to junior developers by using my dialog framework.

I think the community will benefit from having already made dialogs for common scenarios (Greeting, Closing conversation. Request Dialog, Booking, Navigation menu, etc.) and provide a variation of them.

Here are an example of a Greeting collection:
Simple Greeting:
```
Agent: Hello
``` 
Opening Self-Identification
```
Agent: Hello I'm <Bot Name>
```
Opening Name Request
```
Agent: Hello, I'm <Bot Name>, What is your name?
User: <User name>
Agent: Hi, <User Name>
```
Opening Direct Address
```
Agent: Hello <User Name>
User: Hi
```
Opening with menu
```
Agent: Hello I'm <Bot Name>, How can I help you? [option1, option2, option3, etc.]
User: option3
```
From the example above, one developer can greet users just by calling Simple Greeting dialog.
Also a developer can use a greeting variation and just setup the bot name or user name (Opening Self-Identification, Opening Direct Address),
Alternatively a developer can greet user with a more complex interaction (Opening Name Request, Opening with menu, etc.).

This dialogs can be a collection of Adaptive Dialogs, Component Dialogs, etc.

Happy holidays!!

**Comment by garypretty** [comment]
Thank you @sempjc for the suggestion. Please see this link for some details of something the core team at Microsoft are working towards right now which I think aligns with your suggestions https://github.com/microsoft/botframework-components/

**Comment by sempjc** [comment]
Thanks @garypretty for your guidance. I will check the link.
