### ISSUE TITLE
Help requests via the Alexa channel closing conversation

### ISSUE THREAD

**Issue by AndyfromPBG** [BotBuilderCommunity/botbuilder-community-dotnet#359]
Any type of help/I need help requests via the Alexa channel causes my bot to return a command to close the conversation rather than triggering the interruption methods of my bot. For example, this request:
```
{
	"version": "1.0",
	"session": {
		"new": false,
		"sessionId": "amzn1.echo-api.session.4c919862-a7cf-44c3-a630-53e67e7c75a3",
		"application": {
			"applicationId": "amzn1.ask.skill.a5cbe643-6e54-4f01-bf5f-25a4199739b0"
		},
		"user": {
			"userId": ""
		}
	},
	"context": {
		"Viewports": [
			{
				"type": "APL",
				"id": "main",
				"shape": "RECTANGLE",
				"dpi": 160,
				"presentationType": "STANDARD",
				"canRotate": false,
				"configuration": {
					"current": {
						"mode": "HUB",
						"video": {
							"codecs": [
								"H_264_42",
								"H_264_41"
							]
						},
						"size": {
							"type": "DISCRETE",
							"pixelWidth": 1024,
							"pixelHeight": 600
						}
					}
				}
			}
		],
		"Viewport": {
			"experiences": [
				{
					"arcMinuteWidth": 246,
					"arcMinuteHeight": 144,
					"canRotate": false,
					"canResize": false
				}
			],
			"mode": "HUB",
			"shape": "RECTANGLE",
			"pixelWidth": 1024,
			"pixelHeight": 600,
			"dpi": 160,
			"currentPixelWidth": 1024,
			"currentPixelHeight": 600,
			"touch": [
				"SINGLE"
			],
			"video": {
				"codecs": [
					"H_264_42",
					"H_264_41"
				]
			}
		},
		"Extensions": {
			"available": {
				"aplext:backstack:10": {}
			}
		},
		"System": {
			"application": {
				"applicationId": ""
			},
			"user": {
				"userId": ""
			},
			"device": {
				"deviceId": "",
				"supportedInterfaces": {}
			},
			"apiEndpoint": "https://api.amazonalexa.com",
			"apiAccessToken": ""
		}
	},
	"request": {
		"type": "IntentRequest",
		"requestId": "amzn1.echo-api.request.ff38aeab-8dff-4b5a-a68b-a19ad3323f73",
		"locale": "en-US",
		"timestamp": "2021-01-24T00:59:36Z",
		"intent": {
			"name": "AMAZON.HelpIntent",
			"confirmationStatus": "NONE"
		}
	}
}
```
Results in this response:
```
"body": {
		"version": "1.0",
		"response": {
			"outputSpeech": {
				"type": "PlainText",
				"text": ""
			},
			"shouldEndSession": true,
			"type": "_DEFAULT_RESPONSE"
		}
	}
```

I'm hitting my Bot's on turn async method, and then it's going straight to end conversation without even loading my dialog. I'd love to give more info if someone would tell me what else would be useful.

**Comment by arafattehsin** [comment]
Hi @AndyfromPBG - Thanks for the question. Are you using one Alexa's adapters? If I understood your question correctly, you do not want Alexa to close the session. Is it the case?

**Comment by AndyfromPBG** [comment]
Thank you so much for the response! I'm currently using the Alexa channel on the Azure Bot service hosting configuration, but I'm happy to just use the Alexa adapter if it works. My bot is sending a close channel request to Alexa; I'm hoping that instead my bot will see it as an interrupt request and I can then handle it as I do help requests from other channels.

**Comment by AndyfromPBG** [comment]
Update- I tried using the Alexa adapter from this project (sorry, not sure why I posted on here before that) and I see the same problem, so at least it's relevant to this channel now.

I doubt it's the correct way, but I noticed that the help request from Alexa wasn't getting though with any info, so I check to see if Alexa's sending a help request in the OnTurnAsync method of my DialogBot

        public override Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken = default)
        {
            if (turnContext.Activity.ChannelId == "alexa" && turnContext.Activity.Value is Alexa.NET.Request.Type.IntentRequest req && req.Intent.Name == "AMAZON.HelpIntent")
            {
                turnContext.Activity.Type = "message";
                turnContext.Activity.Text = "help";

            }
            return base.OnTurnAsync(turnContext, cancellationToken);
        }

**Comment by garypretty** [comment]
@AndyfromPBG the Alexa Channel in ABS actually uses this adapter under the hood, which is why you are probably seeing the same experience.

The Alexa adapter converts some of the built in Amazon Intents to event activities  https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/d7d91e255ff13886825973b601a711a25550d0cf/libraries/Bot.Builder.Community.Adapters.Alexa.Core/AlexaRequestMapper.cs#L43-L71.

To handle these events you can add an additional method on your bot to handle those events, as seen here in the sample https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/d7d91e255ff13886825973b601a711a25550d0cf/samples/Alexa%20Adapter%20Sample/Bots/EchoBot.cs#L79-L83

I hope that helps clear things up for you - let me know if you have any other questions.
