### ISSUE TITLE
Pro Active Notification V4 Bot

### ISSUE THREAD

**Issue by Silu321** [BotBuilderCommunity/botbuilder-community-dotnet#360]
I am trying to implement an MS-TEAM_BOT that is capable of sending a Pro-Active Notification to a particular MS-TEAM Person

Ex: Database contains ( Student Name, Roll Number (primary key), Fee Payment status)
if fee payment status is pending then the student gets a pro-active notification from the bot. 

can you provide the documentation and code?

**Comment by rvinothrajendran** [comment]
Ref here: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet

**Comment by Silu321** [comment]
this is v3 bot documentation but, I need v4 bot documentation and also can u please read my requirement in my previous issue

**Comment by stephanbisser** [comment]
@Silu321 there is a v4 sample mentioned here: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/16.proactive-messages

Is this sample fulfilling your requirements?

**Comment by rvinothrajendran** [comment]
@Silu321 I have shared the documentation based on 4.6 "The code samples in this section are based on 4.6"

**Comment by Silu321** [comment]
@rvinothrajendran 

my requirement is given below so can you please read it then guide me

-> one SQL database is present
-> that database contains 4 number of Students data
i.e
StudentName = "Ghansyam Gouda",mail="ghansyam.gouda@E", Age = 13, Date =2021/2/1, Flag ="No"
StudentName = "Sumit Vishwakarma",mail="sumeet.vishwakarma@", Age = 21, Date =2021/2/2, Flag ="No"
StudentName = "Divyakanta Acharya",mail="dibyakanta.acharya@", Age = 18, Date =2021/2/3, Flag ="Yes"
StudentName = "Pratush Biswal" ,mail="pratyush.biswal@", Age = 20, Date =2021/2/4, Flag ="No"

then
IF( student Flag="no")
then that time student get a proactive message
else
no operation is done

note
above bot work in-side the ms-team
