### ISSUE TITLE
How to send private message in Microsoft Teams using bot on behalf of user in Teams?

### ISSUE THREAD

**Issue by Silu321** [BotBuilderCommunity/botbuilder-community-dotnet#361]
-> one SQL database is present 
-> that database contains 4 number of Student data
i.e
StudentName = "Ghansyam Gouda",mail="ghansyam.gouda@E", Age = 13, Date =2021/2/1, Flag ="No"
StudentName = "Sumit Vishwakarma",mail="sumeet.vishwakarma@",  Age = 21, Date =2021/2/2, Flag ="No"  
StudentName = "Divyakanta Acharya",mail="dibyakanta.acharya@",  Age = 18, Date =2021/2/3, Flag ="Yes" 
StudentName = "Pratush Biswal" ,mail="pratyush.biswal@", Age = 20, Date =2021/2/4, Flag ="No"

then
 IF( student Flag="no")
then that time student get a proactive message 
else 
no operation is done

note 
above bot work in-side the ms-team

**Comment by ahmetkocadogan** [comment]
Can you please clarify 

> on behalf of user

Bot can send proactive messages, but bot can not send messages on behalf of users.

**Comment by Silu321** [comment]
ok , proactive messages can you provide the code or documentation
 but pls read my requirement

**Comment by stephanbisser** [comment]
As per your other issue (https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/issues/360) the link to the proactive messaging sample is here: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/16.proactive-messages

**Comment by Silu321** [comment]
I don't need this documentation I need an ms-team proactive bot. 


-> one SQL database is present
-> that database contains 4 number of Student data
i.e
StudentName = "Ghansyam Gouda",mail="ghansyam.gouda@E", Age = 13, Date =2021/2/1, Flag ="No"
StudentName = "Sumit Vishwakarma",mail="sumeet.vishwakarma@", Age = 21, Date =2021/2/2, Flag ="No"
StudentName = "Divyakanta Acharya",mail="dibyakanta.acharya@", Age = 18, Date =2021/2/3, Flag ="Yes"
StudentName = "Pratush Biswal" ,mail="pratyush.biswal@", Age = 20, Date =2021/2/4, Flag ="No"

then
IF( student Flag="no")
then that time student get a proactive message
else
no operation is done

note
above bot work in-side the ms-team

**Comment by ahmetkocadogan** [comment]
@Silu321 documentation guides you to build your proactive bot.

If you want someone else to build and give you the bot with your requirements, that is not how these issues work in github and also that is ethically wrong.

**Comment by arafattehsin** [comment]
Closing this issue as it is not relevant for this community repo.
