### ISSUE TITLE
Intent clashes with the Google Adapter

### ISSUE THREAD

**Issue by aishwaryaumachandran** [BotBuilderCommunity/botbuilder-community-dotnet#366]
We have a skill that has skills related to Email/Calendar (Both Office 365)

Any questions related to this domain exits the action and defaults it to Google Email / the Calendar. The sample utterances are given below: 
- Check my calendar 
- Check my emails

This solution was working about a week back. Have anyone faced this issue before and have a potential solution?

**Comment by arafattehsin** [comment]
That's strange. In your DialogFlow, do you have anything set-up out of the box such as Google Email / Calendar?

**Comment by aishwaryaumachandran** [comment]
Thank you for the turnaround Arafat. There is nothing setup on dialog flow in the intents apart from a Welcome and Fallback. 

Further testing the solution, there were a lot of other conflicts with other skills too such as the News, Recipes, etc not limiting to office 365. Anything that is a general "googled" question, exits the action and Google Assistant gives me the result.

**Comment by garypretty** [comment]
@aishwaryaumachandran There is now a dedicated adapter for Actions Builder here https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Adapters.ActionsSDK, so you may need to replace the adapter used by your bot.

Closing this for now, but please let us know how this works for you.

**Comment by aishwaryaumachandran** [comment]
@garypretty Thank you for this. We are almost nearing our upgrade and as per your suggestion. I replaced the adapter with the ActionsSDK one. I am successfully able to connect with the sample and the expected result. 

In terms of the account linking scenario which I have some trouble with, Is there a specific configuration I need to follow for the Azure App Registration? I don't see that in the documentation. Let me know if you have any questions!
