### ISSUE TITLE
How to use the adapter to connect bot with Whatsapp messagebird?

### ISSUE THREAD

**Issue by YeisonsUarez** [BotBuilderCommunity/botbuilder-community-dotnet#378]
Hi, I already have the MessageBird adapter implemented in the Bot code, the keys: "MessageBirdAccessKey", "MessageBirdSigningKey" and the Bot is published in azure. But the messagebird WhatsApp channel still does not connect to the Bot. What can I do?

**Comment by ahmetkocadogan** [comment]
Hello @YeisonsUarez.

I implemented this adapter, i'll try to help you on this.

Are you using WhatsApp sandbox? Did you get the correct AccessKey and SigningKey from MessageBird dashboard ?

**Comment by YeisonsUarez** [comment]
Hi, the AccessKey and SigningKey I got them using the links given in the adapter tutorial, WhatsApp sandbox shows me connected in my personal WhatsApp, but still the Bot does not connect. what am I missing? Thanks for your help.

**Comment by ahmetkocadogan** [comment]
Hello @YeisonsUarez 

Probably you didn't set up the webhook url.

![image](https://user-images.githubusercontent.com/7287309/112988837-f18d5900-916c-11eb-8dda-6871ba328535.png)

**Comment by YeisonsUarez** [comment]
oh, I see, in webhook url, which url should I add?

**Comment by YeisonsUarez** [comment]
oh ok, I didn't see that step, thanks, I'll try it.

**Comment by YeisonsUarez** [comment]
In that case it would only work in WhatsApp sandbox ? how can I make it work in WhatsApp channel ? thank you very much for your help.

**Comment by ahmetkocadogan** [comment]
+ and also this parameter should be false if you are not using sandbox
"MessageBirdUseWhatsAppSandbox": true

**Comment by YeisonsUarez** [comment]
I understand, I will apply it, thank you very much for helping me.

**Comment by ahmetkocadogan** [comment]
> I understand, I will apply it, thank you very much for helping me.

Your welcome. You can close the issue if you feel your question is answered.

**Comment by YeisonsUarez** [comment]
One last question, in the WhatsApp channel where do I add the Bot URL?

**Comment by ahmetkocadogan** [comment]
https://developers.messagebird.com/quickstarts/conversations/handle-inbound-messages-curl/

On this page, there is a section "Programmatically configure webhooks via the API"

You will make a post request to conversations endpoint of MessageBird, with your endpoint url that you created for MessageBird WhatsApp Adapter.

```
curl -X "POST" "https://conversations.messagebird.com/v1/webhooks" \\
-H "Authorization: AccessKey YOUR-API-KEY" \\
-H "Content-Type: application/json" \\
--data '{
"events":["message.created", "message.updated"],
"channelId": "CHANNEL-ID",
"url":"https://example.com/webhook"
}'
```

**Comment by ahmetkocadogan** [comment]
And for more information for you, this adapter is not an official adapter from MessageBird. 

I am maintaining it. There is a newer version of their NuGet package, but it has an issue with sandbox, only works for production at the moment. I am waiting their fix, and will update this adapter as soon as they fix it.

Feel free to ask anything about this adapter. Also check out sample bot in samples directory. Thanks.

**Comment by YeisonsUarez** [comment]
Hi, I have made the changes with the correct credentials and url but still I can't connect the Bot with messagebird, the user messages appear in inbox but nothing is returned.  :( do you think I missed something? Thanks for your help. I am trying to connect with whatsapp.

**Comment by ahmetkocadogan** [comment]
hello @YeisonsUarez .

I want to kindly ask you to try sample project first. Sample project will work with correct credentials and set up. You can use sandbox to test. Just let me know what the result is with that test. Than we'll start digging what is your issue. 

Sounds nice?

**Comment by YeisonsUarez** [comment]
Ok, I will try it, thank you very much

**Comment by ahmetkocadogan** [comment]
@YeisonsUarez Hello. Any luck with sample project ?

**Comment by garypretty** [comment]
Thanks for your help here @ahmetkocadogan - really appreciate you helping @YeisonsUarez through these issues!

Closing this for now - @YeisonsUarez please re-open if you need further assistance.
