### ISSUE TITLE
Add tag to LivePerson package

### ISSUE THREAD

**Issue by clearab** [BotBuilderCommunity/botbuilder-community-dotnet#386]
In order for Package Manager to consume a package that doesn't have a schema files, the package must be tagged with one of the following:

`msbot-action` || `msbot-trigger` || `msbot-adapter` || `msbot-function` || `msbot-recognizer` || `msbot-storage` || `msbot-middleware`

For this package, I believe `msbot-middleware` makes the most sense.

**Comment by garypretty** [comment]
New release pushed to NuGet which has the msbot-middleware tag.
