### ISSUE TITLE
Organization, repos, and structure?

### ISSUE THREAD

**Issue by szul** [BotBuilderCommunity/botbuilder-community-dotnet#4]
Any reason not to create a GitHub org and add us all to it? Then each project could be broken out into a separate repository without clogging @garypretty's account? If this repository continues to grow, and incorporates, let's say, 10x more extensions, it's going to create overhead for cloning, testing, etc., and might be more difficult to maintain.

My proposal:

* Create a BotBuilder Community GitHub org
* Add everyone to it
* Transfer ownership of repos to the Org
* Break apart botbuilder-community repo into individual parts
* Anyone else with personal bot repos (such as me) can follow whatever structure best practices are used, and then transfer those repos to the Org as well.

Each individual repo could have subfolders for dotnet, python, java, and nodejs for the supported languages. It would also allow each repo to have it's own CI script for build, test, deploy.

On the Node.JS end, NPM allows for "orgs" as well, and for free as long as the packages are public. For the Node.JS tools I've already created, I can transfer ownership of the packages to the org. I'd have to check to see how Travis CI handles builds, but it's based off of granting privileges to the orgs, so it might just be a permissions thing.

Thoughts?

**Comment by garypretty** [comment]
@szul I am not opposed to this, but I believe having a GitHub org costs minimum $25 per month for the first 5 users and then an additional $9 per month per user after that.  Hence me creating the repo under my account. Ideally I wanted to see what traction we got before we got into anything commercial.

**Comment by garypretty** [comment]
@szul Certainly not opposed to creating a separate repos though for node etc. We could rename the one that is there now to botbuilder-community-dotnet and then have a second botbuilder-community-js, which keeps it in line with MS repo naming.  I am not too concerned about having the repos on my account at this stage.  Let me know if you want me to get a JS repo setup and I can get you added.

**Comment by szul** [comment]
@garypretty I have 4 orgs myself. Never been charged. I think orgs are free unless you want private repos or a business account. [This](https://blog.github.com/2010-06-29-introducing-organizations/) really old blog posts says it's "free for open source".

**Comment by garypretty** [comment]
Ok. In that case, let me take a look later and I can get the wheels in motion as I think it makes sense.

**Comment by szul** [comment]
Okay, I'll read up on NPM orgs then. That way, if you decide to go in the orgs direction, both the deployment packages (for Node.JS) and source control are aligned.

**Comment by garypretty** [comment]
@szul I am going to create an org called BotBuilderCommunity, which happily matches the org name I created on NuGet.  We can then transfer the repo over to this org. What is everyone's thoughts on renaming the current repo to botbuilder-community-dotnet and creating a second botbuilder-community-js? @jamesemann @arafattehsin

**Comment by garypretty** [comment]
@szul Whilst waiting for the others to come back to me, do you want to go ahead when you get a chance and secure the BotBuilderCommunity org name on NPM when you get a chance?

**Comment by arafattehsin** [comment]
It's absolutely fine to go for the name as **botbuilder-community-dotnet, botbuilder-community-js** and so on.

**Comment by jamesemann** [comment]
All makes sense. Think this will be a good way forward 👍 @szul my npm account is jamesemann

**Comment by szul** [comment]
@jamesemann Done.

**Comment by garypretty** [comment]
Ok, I am going to move ahead with this move tonight or tomorrow (hopefully tonight). At a high level I don't think it is a problem having a number of extensions etc. within a single repo, in the same way that the bot team have multiple packages within the same repo for the SDK.  I do think it makes sense to split out by language.  To that end I think it also makes sense to have a separate repo for tools - thus keeping us in line with the MS repos, which will help people find what they need too.

As a start, here is what I am planning to create.

 - **botbuilder-community-dotnet** (move and rename the current repo).  This will be the home of all .NET extensions (i.e. middleware, dialogs etc).  Each extensions has its own folder within the libraries folder and therefore its own readme.  Readmes follow the same structure we have in place now which we can tweak in the future.

 - **botbuilder-community-js**. Same as above but for the Node side of things. Each extension / component has its own folder and again its own readme.  Hopefully readmes can follow a similar / same structure as the .NET components.

 - **botbuilder-community-tools**. This repo can be the community counterpart for the botbuilder-tool repo.  I think each tool would have its own folder, with again its own readme.  I think this will be the right place to move @szul's code project too. I.e. dedicated folder within this repo.

Main readme for each repo outlines and links to the various components and their associated readmes within the repo.

@szul I have almost zero experience on the JS side of things - would you be happy to help lead in this repo and helping with automated builds etc? Obviously if anyone else has experience please shout up.

**Comment by szul** [comment]
@garypretty I have no problem doing what I can on the Node.JS side, including with the builds and pushes to NPM, etc.

Can you create a botbuilder-community-python repo as well? It's early stages, but I was starting to write a Python version of the botbuilder-config.

**Comment by garypretty** [comment]
@szul sure, no problem!

**Comment by garypretty** [comment]
@szul @arafattehsin @jamesemann Ok, all done. Org created - added you all. Created the 3 additional repos and started them with their opening readme titles and paragraphs to keep them consistent.  Looking forward to see what we can do here with this broader view.
