### ISSUE TITLE
how to limit auto scrolling in chat window

### ISSUE THREAD

**Issue by Akash-Chatti** [BotBuilderCommunity/botbuilder-community-dotnet#432]
When the web chat bot sends a long adaptive card with menu along with the text message at the top, the chat window scrolls down hiding the text.

I need to limit the auto scroll of chat window to show the text message i.e., to scroll till start of message instead of end of message.

How to achieve this

**Comment by rvinothrajendran** [comment]
Please post general questions in https://stackoverflow.com/questions/tagged/botframework
