### ISSUE TITLE
 The MessageBird adapter for WhatsApp does not work when using special Spanish characters

### ISSUE THREAD

**Issue by JustZeus** [BotBuilderCommunity/botbuilder-community-dotnet#435]
@ahmetkocadogan I appreciate your contributions very much! Thanks for maintaining this adapter

I have managed to use the  MessageBird adapter for WhatsApp in a bot created using the composer bot, modifying the source code I made the adapter work properly with the Messagebird sandbox.

The problem is that the bot does not respond at all if I use words with special characters in Spanish such as Á, É, Í, Ó, Ú, and Ñ.

Will it have to do with the encoding at the time the adapter deserializes the JSON to convert it into a variable in C#?

**Comment by ahmetkocadogan** [comment]
Hello @JustZeus . I am glad if this adapter is useful for you, thank you.

I need to debug and test this cituation to identify the couse, but i am in holiday and will be using a computer next monday. I wanted to let you know so you don't think i am not watching :)

I'll update this issue when i test and identify this issue as soon as i can. 

Have a good day.

**Comment by ahmetkocadogan** [comment]
Hello @JustZeus 

I tried the adapter with the letters you send in this issue, like below:

![image](https://user-images.githubusercontent.com/7287309/127133566-0eaa0d0e-ed16-4fb6-a847-09e581c4d121.png)

And looks like i can see the letters without a problem.

![image](https://user-images.githubusercontent.com/7287309/127133607-d3b42eba-5e3c-42ee-85b2-c996f073cd09.png)

I am not an expert about hosting settings, but, can this be an issue with your hosting settings, language or region settings on the machine that you host the bot ?

**Comment by JustZeus** [comment]
Hello! hope you had a great holiday, thank you very much for your support.

Oh, now I see that maybe is not because of the adapter, it could be the web server config instead.

The bot is hosted in an Azure Web App, I developed the bot using the bot framework composer application for windows, I started with the basic QnA template for C#. Then I modified the source code generated from the composer to add the message Bird Adapter and finally I published the bot using the composer's deployment tools



<img src="https://user-images.githubusercontent.com/46466785/127223634-0a188d42-9db3-4e4a-ab00-0b7c8e1deb1d.jpg" width="300">


As you can see it only sends a response if I send a word without special characters, but in another channels like telegram and web chat it works fine.

now I'm clueless about the problem, ¿Any suggestions for debugging? 

Thank you very much in advance : )

**Comment by ahmetkocadogan** [comment]
Hello @JustZeus .

Since i can send and receive that special letters, i think you have one more option to try.

Run your bot project locally, setup ngrok, use ngrok url for webhook for WhatsApp sandbox, and type that letter in WhatsApp to the bot. Then inspect ngrok, you can see incoming network requests. If you don't see a webhook request is coming, then we can say it is MessageBird's API that does not transmit the message, if you see the request is coming, then we can say it is the adapter and maybe dive deeper.

And, is there any chance for you to try it in production (via a verified WhatsApp number), not with a WhatsApp sandbox?

**Comment by JustZeus** [comment]
I tried with an Azure Functions like Webhook and MessageBird correctly sends the messages with the special characters of Spanish, the problem is not in MessageBird.  I still do not have my registered number 

I configured my development environment to debug the application locally and use ngrok as you mentioned, when I send normal text it responds with 200 responses but as soon as I use some
character in Spanish only returns me 401 Unauthorized

Could it be that it detects those characters as malicious text?

thanks for all your support!

**Comment by ahmetkocadogan** [comment]
Hello @JustZeus .

I'll debug the adapter again. With the last info you give, it looks like adapter cousing the issue. Interesting part is, i was able to send and receive that letters without any issue.

I'll dive deeper and debug line by line. I'll let you know when i'm done.

Thank you.

**Comment by JustZeus** [comment]
Thank you @ahmetkocadogan ,  you are exceptional!

If you want to replicate the environment completely, you can create a project using the bot framework composer, a simple template like the one from LUIS or QnA, and edit the generated code by adding the adapter.

Perhaps the problem is in the integration of the adapter in such projects.

I am here to support you if you need it.

**Comment by ahmetkocadogan** [comment]
Hello @JustZeus .

I think i find the issue, i still didn't have time to debug but i inspected my code. Because it gives 401, it should be request verification failing.

This is the part that i read body of the request with StreamReader:

![image](https://user-images.githubusercontent.com/7287309/128046587-745fee4f-4b72-4830-8356-bc84dcf8a7a0.png)

And this is the method i call to verify the message : 

![image](https://user-images.githubusercontent.com/7287309/128046629-41777a7c-4956-4d79-86f4-7f9c1603e854.png)

Probably, reading the body in the first picture with StreamReader needs an encoding. This is what i understand with inspecting the code with the info that it returns 401 Unauthorized.

I'll let you know when i debug.

If you can, you can dowload the adapter project and add to your code, modify the StreamReader with encoding, instead of using adapter from NuGet, and check the results, till i find time and inspect it myself.

Have a good day.

**Comment by JustZeus** [comment]
Thank you very much for your support! with your recommendations I was able to solve my problem, now it works wonderfully.
I created a pull request if you are interested in seeing my solution and comment on it if you think it's necessary.

Again, I really appreciate the time you invested in this situation 👍

**Comment by ahmetkocadogan** [comment]
@JustZeus I am so sorry for making you wait this long. I couldn't have time to debug it again and update you on this.

I am so glad that you resolved the issue,  really appreciate your efforts to create that pull request, and making me feel useful with using this adapter :)

 Have a nice day.

**Comment by JustZeus** [comment]
@ahmetkocadogan Hello again! 
Hope you are doing very well.

I just acquire my WhatsApp channel, any recommendation to use this adapter in production? 

Thank you very much in advance:)

**Comment by ahmetkocadogan** [comment]
@JustZeus I don't know what to recommend to you to be honest :) It is an adapter that i coded for my needs, i use it for my production bots without an issue. 

Also via Messagebird, from sandbox to production, i had no issue about their service. 

One mistake i made was, i only handled text messages from bot and in production someone sended an image, boomm app crash :) Make sure that you test and handle all possible message types.

**Comment by drmanhatin** [comment]
@JustZeus can you share some code on how to register the IBot? I just started with bot framework composer, now I'm looking to add the messagebird extension aswell.

**Comment by ahmetkocadogan** [comment]
@JustZeus  Hello. If you can share how you use MessageBird library with bot framework composer, we can also update our readme and guide people who wanna use it.

**Comment by JustZeus** [comment]
I’m sorry for the time to answer, I was on my holyday.

Yes of course I can show you!!, It’s very straight forward

I have to say that this is what worked for me but don’t necessary mean that it is the best way to do it.

**1.-Step One**

Select a template with C#
 
![image](https://user-images.githubusercontent.com/46466785/149643617-b6aa38ff-96f9-4b20-bbbb-0b1f25168f5e.png)


**Step 2.- Select Azure Web App as an execution time.**

When selected and confirmed the bot Framework Composer will create the project in your selected directory.

![image](https://user-images.githubusercontent.com/46466785/149643630-f2670223-40ba-4b76-b475-93c2d7bfff32.png)

 
**Step 3.- Open bot’s directory**

Once you navigate to the bot’s directory you should see a .sln file (Visual Studio Solution) you can install a version of Visual Studio for your C# bot framework development if you are using Bot Composer. If you prefer you can also do the modifications with a code editor.
 
![image](https://user-images.githubusercontent.com/46466785/149643637-11c7efab-2b3f-4875-be69-79d30b56c324.png)

**Step 4.- Open Bot’s .sln file and edit source code**

This will open the project in Visual Studio, here you can navigate to the source code generated by the bot composer
First you need to add the package reference to the .csproj file in the project´s directory
 
![image](https://user-images.githubusercontent.com/46466785/149643643-c7c4d84c-8e91-4e41-82b5-fff81a9284cf.png)


**Step 5.- Follow the steps as shown in the README.md in the adapter repository** [botbuilder-community-dotnet/libraries/Bot.Builder.Community.Adapters.MessageBird at develop · BotBuilderCommunity/botbuilder-community-dotnet (github.com)](url) 

Use the sample code as reference to modify the source code of the Bot project generated by Bot Composer

  **_Sample:_**
[botbuilder-community-dotnet/samples/MessageBird Adapter Sample at develop · BotBuilderCommunity/botbuilder-community-dotnet (github.com)](url)

-	You need to add the appsettings.json file to the project’s root directory

-	Create an MessageBird adapter class, create a MessageBirdAdapterWithErrorHandler.cs file as in the sample

-	Add the controller file (MessageBirdController.cs) to the “Controllers” directory in the bot’s source code.
 
![image](https://user-images.githubusercontent.com/46466785/149643647-c50b0665-8d41-44d2-ace0-879da9a68603.png)

-	Add the singletons to the Startup.cs file 

 
![image](https://user-images.githubusercontent.com/46466785/149643651-63a9b380-335e-45d2-98f5-ac50037154f7.png)



Finally, you can start testing it!! Remember to add tour credentials in the “appsettings.json” file

As I said you can follow the sample's methodology.

Hope this helps, I’m here if you need more information, also suggestions are welcome if you see points of improvement. 

**Ricardo Z.**

**Comment by rvinothrajendran** [comment]
@JustZeus Thanks for sharing & will do it the best way.
@ahmetkocadogan I will convert this adapter to fit the bot composer component later will update the readme file.

**Comment by saikumaru** [comment]
@JustZeus - can you please check and confirm if this procedure still works, I tried to replicate, but it doesnt work. Bot receives the message, but is unable to respond.

Also, did you use Sandbox for this test or the actual whatsapp number?

> I’m sorry for the time to answer, I was on my holyday.
> 
> Yes of course I can show you!!, It’s very straight forward
> 
> I have to say that this is what worked for me but don’t necessary mean that it is the best way to do it.
> 
> **1.-Step One**
> 
> Select a template with C#
> 
> ![image](https://user-images.githubusercontent.com/46466785/149643617-b6aa38ff-96f9-4b20-bbbb-0b1f25168f5e.png)
> 
> **Step 2.- Select Azure Web App as an execution time.**
> 
> When selected and confirmed the bot Framework Composer will create the project in your selected directory.
> 
> ![image](https://user-images.githubusercontent.com/46466785/149643630-f2670223-40ba-4b76-b475-93c2d7bfff32.png)
> 
> **Step 3.- Open bot’s directory**
> 
> Once you navigate to the bot’s directory you should see a .sln file (Visual Studio Solution) you can install a version of Visual Studio for your C# bot framework development if you are using Bot Composer. If you prefer you can also do the modifications with a code editor.
> 
> ![image](https://user-images.githubusercontent.com/46466785/149643637-11c7efab-2b3f-4875-be69-79d30b56c324.png)
> 
> **Step 4.- Open Bot’s .sln file and edit source code**
> 
> This will open the project in Visual Studio, here you can navigate to the source code generated by the bot composer First you need to add the package reference to the .csproj file in the project´s directory
> 
> ![image](https://user-images.githubusercontent.com/46466785/149643643-c7c4d84c-8e91-4e41-82b5-fff81a9284cf.png)
> 
> **Step 5.- Follow the steps as shown in the README.md in the adapter repository** [botbuilder-community-dotnet/libraries/Bot.Builder.Community.Adapters.MessageBird at develop · BotBuilderCommunity/botbuilder-community-dotnet (github.com)](url)
> 
> Use the sample code as reference to modify the source code of the Bot project generated by Bot Composer
> 
> **_Sample:_** [botbuilder-community-dotnet/samples/MessageBird Adapter Sample at develop · BotBuilderCommunity/botbuilder-community-dotnet (github.com)](url)
> 
> * You need to add the appsettings.json file to the project’s root directory
> * Create an MessageBird adapter class, create a MessageBirdAdapterWithErrorHandler.cs file as in the sample
> * Add the controller file (MessageBirdController.cs) to the “Controllers” directory in the bot’s source code.
> 
> ![image](https://user-images.githubusercontent.com/46466785/149643647-c50b0665-8d41-44d2-ace0-879da9a68603.png)
> 
> * Add the singletons to the Startup.cs file
> 
> ![image](https://user-images.githubusercontent.com/46466785/149643651-63a9b380-335e-45d2-98f5-ac50037154f7.png)
> 
> Finally, you can start testing it!! Remember to add tour credentials in the “appsettings.json” file
> 
> As I said you can follow the sample's methodology.
> 
> Hope this helps, I’m here if you need more information, also suggestions are welcome if you see points of improvement.
> 
> **Ricardo Z.**

**Comment by saikiranvarmaJSN** [comment]
> @JustZeus - can you please check and confirm if this procedure still works, I tried to replicate, but it doesnt work. Bot receives the message, but is unable to respond.
> 
> Also, did you use Sandbox for this test or the actual whatsapp number?
> 
> > I’m sorry for the time to answer, I was on my holyday.
> > Yes of course I can show you!!, It’s very straight forward
> > I have to say that this is what worked for me but don’t necessary mean that it is the best way to do it.
> > **1.-Step One**
> > Select a template with C#
> > ![image](https://user-images.githubusercontent.com/46466785/149643617-b6aa38ff-96f9-4b20-bbbb-0b1f25168f5e.png)
> > **Step 2.- Select Azure Web App as an execution time.**
> > When selected and confirmed the bot Framework Composer will create the project in your selected directory.
> > ![image](https://user-images.githubusercontent.com/46466785/149643630-f2670223-40ba-4b76-b475-93c2d7bfff32.png)
> > **Step 3.- Open bot’s directory**
> > Once you navigate to the bot’s directory you should see a .sln file (Visual Studio Solution) you can install a version of Visual Studio for your C# bot framework development if you are using Bot Composer. If you prefer you can also do the modifications with a code editor.
> > ![image](https://user-images.githubusercontent.com/46466785/149643637-11c7efab-2b3f-4875-be69-79d30b56c324.png)
> > **Step 4.- Open Bot’s .sln file and edit source code**
> > This will open the project in Visual Studio, here you can navigate to the source code generated by the bot composer First you need to add the package reference to the .csproj file in the project´s directory
> > ![image](https://user-images.githubusercontent.com/46466785/149643643-c7c4d84c-8e91-4e41-82b5-fff81a9284cf.png)
> > **Step 5.- Follow the steps as shown in the README.md in the adapter repository** [botbuilder-community-dotnet/libraries/Bot.Builder.Community.Adapters.MessageBird at develop · BotBuilderCommunity/botbuilder-community-dotnet (github.com)](url)
> > Use the sample code as reference to modify the source code of the Bot project generated by Bot Composer
> > **_Sample:_** [botbuilder-community-dotnet/samples/MessageBird Adapter Sample at develop · BotBuilderCommunity/botbuilder-community-dotnet (github.com)](url)
> > 
> > * You need to add the appsettings.json file to the project’s root directory
> > * Create an MessageBird adapter class, create a MessageBirdAdapterWithErrorHandler.cs file as in the sample
> > * Add the controller file (MessageBirdController.cs) to the “Controllers” directory in the bot’s source code.
> > 
> > ![image](https://user-images.githubusercontent.com/46466785/149643647-c50b0665-8d41-44d2-ace0-879da9a68603.png)
> > 
> > * Add the singletons to the Startup.cs file
> > 
> > ![image](https://user-images.githubusercontent.com/46466785/149643651-63a9b380-335e-45d2-98f5-ac50037154f7.png)
> > Finally, you can start testing it!! Remember to add tour credentials in the “appsettings.json” file
> > As I said you can follow the sample's methodology.
> > Hope this helps, I’m here if you need more information, also suggestions are welcome if you see points of improvement.
> > **Ricardo Z.**

Hi all, 
I also followed same steps. I am using Message Bird's Whatsapp Sandbox. I have checked with ngrok, Bot received request from messagebird and responded with 200 ok. but i can't see any message in whatsapp.

I have tested with v4.13.2 and v4.13.3.
1). With v4.13.2 messages were like this:

![WhatsApp Image 2022-06-07 at 5 08 18 PM](https://user-images.githubusercontent.com/89576203/172371591-dca4db94-c133-4fef-9923-dee79490d9e9.jpeg)

I have sent Hi message and it triggered OnMessageReceived Activity in Bot Service and Bot service responded with some text message(highlighted with green boxes).  "Sorry, it looks like something else" is also from bot. but this message is due to some error in Adapter code that I still haven't figured out.

2). With v4.13.3, Bot responded with 200 ok. But i can't see any message in Whatsapp.

**Comment by ahmetkocadogan** [comment]
hello @saikiranvarmaJSN 

I suggest you to try with a verified WhatsApp number if you have one.

If you don't have one, and want to use sandbox, can you please contact MessageBird support, with referring this issues i created ? 

https://github.com/messagebird/csharp-rest-api/issues/89
https://github.com/messagebird/csharp-rest-api/pull/87

I am currently using version 3 of the MessageBird C# sdk, they made some changes with v3 and removed a parameter that we used to set to true while using sandbox, with explanation that parameter is no longer needed. 

I check it regularly but looks like sandbox functionality is somehow broken, does not work with MessageBird v3 C# sdk.

I guess this might be your issue.
