### ISSUE TITLE
ActionsSDK - Retrieving token from the ChannelData

### ISSUE THREAD

**Issue by aishwaryaumachandran** [BotBuilderCommunity/botbuilder-community-dotnet#436]
Hi, 

I was able to successfully connect with the Actions SDK adapter and even enable the account linking flow using the Azure AD v2. I was wondering if there was a way to get the token in the channel data? 

Any leads are appreciated! Thanks!

**Comment by rvinothrajendran** [comment]
Please post general question in https://stackoverflow.com/
