### ISSUE TITLE
Verify MessageBird Webhooks with new way using MessageBird-Signature-JWT

### ISSUE THREAD

**Issue by ahmetkocadogan** [BotBuilderCommunity/botbuilder-community-dotnet#466]
Documentation for request verification : 
https://developers.messagebird.com/api/#verifying-http-requests

> MessageBird-Signature and MessageBird-Request-Timestamp headers are being deprecated in favor of the MessageBird-Signature-JWT header. We recommend that you update your request validation to ensure better security.

Messagebird WhatsApp adapter needs to be updated with new way of request verification. According to MessageBird documentation, current way is being deprecated and should be updated.

I'll try to take care of this update.

**Comment by ahmetkocadogan** [comment]
@rvinothrajendran Hello.

When i update MessageBird WhatsApp Adapter code, there will be some breaking changes and that changes needs to be reflected to the Composer component you added. Do you want me to notify you when i am done with the code update ?

**Comment by rvinothrajendran** [comment]
@ahmetkocadogan yes please
