### ISSUE TITLE
Cant translate Adaptive Cards in my Azure Bot (Response status code does not indicate success: 401 (Unauthorized))

### ISSUE THREAD

**Issue by deetwo-id** [BotBuilderCommunity/botbuilder-community-dotnet#468]
I am trying to translate an Adaptive Card inside my bot but i always get an authorization error message as shown here:

![image](https://user-images.githubusercontent.com/39704877/155333032-f7a9f997-e109-4f2c-a64e-d9c91cf27076.png)

![image](https://user-images.githubusercontent.com/39704877/155332427-4e0e37e8-8589-469a-81cc-7a18c2ce5f19.png)

`System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Bot.Builder.Community.Cards.Translation.AdaptiveCardTranslator.<>c__DisplayClass17_0`1.<<TranslateAsync>b__0>d.MoveNext()`

I am pretty new to this and maybe it is just a simple fix but i cant find the possible way to the solution. Or maybe i am missing a very important part of the instructions. I chat with the bot locally for testing purposes and also because of that, i use the echo bot sample to have a clean architecture.

My first goal is to just save the translated card in a variable and work with that later on.

![Screenshot 2022-02-23 150037](https://user-images.githubusercontent.com/39704877/155334196-3774ffa8-5fbf-452f-bcb7-868839b83424.png)

`
            System.Diagnostics.Debug.WriteLine("### Start TranslationCard");
            var untranslatedCard = File.ReadAllText(@"C:\Users\PC\Desktop\02.echo-bot\WelcomeCard.json");
            System.Diagnostics.Debug.WriteLine(untranslatedCard);

            System.Diagnostics.Debug.WriteLine("### New HttpClient");
            HttpClient httpClient = new HttpClient();

            System.Diagnostics.Debug.WriteLine("### Translation Process");
            var translatedCard = await AdaptiveCardTranslator.TranslateAsync(
                untranslatedCard,
                "<Access Key from the Translation Service in Azure>",
                "es-es",
                httpClient);

            System.Diagnostics.Debug.WriteLine(translatedCard);
            System.Diagnostics.Debug.WriteLine("### End TranslationCard");
`

![Screenshot 2022-02-23 145708](https://user-images.githubusercontent.com/39704877/155333775-6103d6d1-3ca1-48b8-82d1-092845aa6cf7.png)

**Comment by martinlarosa** [comment]
I think you should be trying to translate individual text, not json structures.
I'm inclined to think that's the first problem and that the api for some reason is throwing a 401 instead of another error?

**Comment by iliosana** [comment]
I also got a 401 Unauthorized error. In my case it was because my Translator Azure instance wasn't in Location/Region global.

**Comment by deetwo-id** [comment]
@iliosana Yup, that worked for me. Problem solved, thank you!
