### ISSUE TITLE
Feature Request: DialogFlow from Json config file

### ISSUE THREAD

**Issue by Brambi-Amb** [BotBuilderCommunity/botbuilder-community-dotnet#47]
Hi Community.
This is a feature request.
Sorry if I am wrong but I am a newbie.
It could be useful that the FlowForm Sample reads a Json file to create menus instead of having _dialogs.Add(FormDialog.FromForm(..)) predefined in the code.
Thanks

**Comment by garypretty** [comment]
This functionality was available in v3 FormFlow, but has not been migrated for v4.  At this time I am afraid there is no plan for this core team to tackle this due to other priorities.
