### ISSUE TITLE
Alexa Adapter Conversation Id Length, Use SessionId Instead?

### ISSUE THREAD

**Issue by brazierdavid** [BotBuilderCommunity/botbuilder-community-dotnet#48]
We have tried using the Alexa adapter with a bot based on the Enterprise Template and hit a problem with Azure blob storage of conversation state, because it uses the conversation id as blob name, but in the Alexa adapter these ids are too long - they are formed as `{Alexa request Application Id}:{Alexa Request User Id}` which can be >270 characters, the blob name limit is 255.  I appreciate the Alexa way of dealing with conversation/session state is to put them in `context.AlexaSessionAttributes` but we'd rather re-use the blob storage approach from the Enterprise Template.  I notice the Alexa sessionId is a much shorter UUID based one:

`"sessionId": "amzn1.echo-api.session.69cf432d-a44b-4319-893d-ed848e040265"`

So could that be used as the Bot Framework conversation id instead?  I will give it a try but any thoughts appreciated.

David

**Comment by garypretty** [comment]
Hi @brazierdavid. Thanks for reaching out with this one.  I think using session ID would make sense.  If you can give this a go and let me know how you get on, then I would be happy to get this change in here and update the NuGet package.

Out of interest, how did you find the on-boarding process with the adapter with the readme etc?  I am keen to understand if the current docs make the adapter easy to understand / use (bearing in mind it is intended to be used by someone who is already familiar with the bot framework generally).

**Comment by brazierdavid** [comment]
See pull request.  My original comment about the blob name wasn't quite right, actually the blobs were saving ok but couldn't then be retrieved because the resulting path name was too long.  However the Enterprise Template uses Cosmos DB for conversation/user state and that does have a 255 limit on document keys.  So either way, using very long conversations ids isn't compatible with the Enterprise Templates.  Using the Alexa session id instead resolves this.

**Comment by garypretty** [comment]
Addressed with #49
