### ISSUE TITLE
Slack Adapter - Duplicate messages for operations longer than 3 seconds

### ISSUE THREAD

**Issue by davidgerrard** [BotBuilderCommunity/botbuilder-community-dotnet#491]
Hi,

I'm currently moving to using the Slack Adapter (previously using Slack channel support), but finding that if an operation takes longer than 3 seconds to process, Slack will send the message again.

I did not see this issue using the channel, so is this a bug in the slack adapter?

I did see a similar issue raised here: https://github.com/microsoft/botbuilder-dotnet/pull/5405

There was an associated commit with that, which looks to have never made it in. 

I'd like to use the Slack adapter because of the block kit support - which still isn't supported in the channel offering.

Thanks

**Comment by davidgerrard** [comment]
It looks like a new message is sent from the user's Slack client, with the same content. There looks to be a new identifier, so I wouldn't be able to filter these duplicates out. You can reproduce the issue if you take the Slack adapter example and add in

`await Task.Delay(3000);`

to the OnMessageActivityAsync method, before the echoed response is sent.

Slack Adapter Sample: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/samples/Slack%20Adapter%20Sample

**Comment by ahmetkocadogan** [comment]
I'm not familiar with Slack payload, but is it possible for you to copy the code of the adapter into your project, instead of NuGet packagr, then inspect the incoming payload from slack webhook request?

libraries/Bot.Builder.Community.Adapters.Slack/SlackHelper.cs

Maybe slack is sending a unique identifier for the message but ToActivity converters does not include that value while converting the payload to activity?

**Comment by ahmetkocadogan** [comment]
Hello @davidgerrard 

I inspected the Slack adapter code and Slack documentation a bit, and as i understand, https://api.slack.com/messaging/retrieving#individual_messages `ts` and `thread_ts` values are unique identifiers of the message.

https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Slack/SlackHelper.cs

Here, as i see, while converting the incoming payload to activity, payload is assigned to `activity.ChannelData` and also there is this assignment `activity.Conversation.Properties["thread_ts"] = slackPayload.ThreadTs`

So, if i understand it correctly, you should be able to read and cache those  `ts` and `thread_ts` values and put a logic to handle it only once.

**Comment by davidgerrard** [comment]
Hi, these are unique each time, as Slack is sending a new message attempt by the looks of it.

Basically we are wanting to launch into waterfall dialogs and so this initialisation etc is just too long. I have tested the workaround in the linked issue and it seems to do what we need. Slack gets a fast response and we resume the conversation when ready, which sometimes is less than 3 seconds, sometimes just over. Depends on the load.

**Comment by ppanchal-mobiz** [comment]
@davidgerrard, I am also facing the same issue where Slack is sending the message multiple times and my `OnMessageActivityAsync` is called more than once. I am also launching waterfall dialogs. Could you please share the link where you found the workaround? Thank you.
