### ISSUE TITLE
Unable to cast object of type 'System.Int64' to type 'Bot.Builder.Community.Dialogs.FormFlow.FormOptions'

### ISSUE THREAD

**Issue by nhadro** [BotBuilderCommunity/botbuilder-community-dotnet#51]
When using a FormFlow I am getting the error "Unable to cast object of type 'System.Int64' to type 'Bot.Builder.Community.Dialogs.FormFlow.FormOptions'".  Essentially what is happening is that the FormOption is getting saved as a enum to the state, but when it is read again, it is read as a integer, not a enum.  This is causing the above exception.  If I don't catch this exception it throws the error and moves on which is why the samples work.  If you have a global exception catch, it errors out.

Something like this on line 292 of the FormDialog class fixes it.(FormOptions)Enum.ToObject(typeof(FormOptions), outerDc.ActiveDialog.State[nameof(_options)])

**Comment by EricDahlvang** [comment]
Thanks @nhadro
