### ISSUE TITLE
Ability to send a proactive message directly to slack without the user interaction

### ISSUE THREAD

**Issue by raghavsuriya** [BotBuilderCommunity/botbuilder-community-dotnet#515]
Hi ,
I am exploring on how to send proactive notifications through the bot framework in slack. Currently it seems that the conversation reference is required to send a new message initiated by the bot. Is it possible to directly send by constructing the conversation reference with the slack user Id, bot ID ?

**Comment by rvinothrajendran** [comment]
Please post a general question in [stackoverflow](https://stackoverflow.com/questions/tagged/botframework)

**Comment by ppanchal-mobiz** [comment]
@raghavsuriya were you able to implement this functionality? Can you please post your solution or StackOverflow question link here? Thank you.
