### ISSUE TITLE
What is the best framework for performance testing of Bot framework V4

### ISSUE THREAD

**Issue by sudheeriilm** [BotBuilderCommunity/botbuilder-community-dotnet#519]
Hi Team,

We are looking for the best framework for performance testing which is compatible with Microsoft chatbot framework V4
We have user C# to develop the bot.

Thanks in advance for your support.

**Comment by rvinothrajendran** [comment]
Please post a general question in [stackoverflow]( https://stackoverflow.com/questions/tagged/botframework)
