### ISSUE TITLE
Usability of GoogleAdapter

### ISSUE THREAD

**Issue by damadei** [BotBuilderCommunity/botbuilder-community-dotnet#56]
Hi all,

I'm trying to use the Google Bot Adapter and having some issues, first had to adapt the path to /api/actionrequest which is different from the documentation.

After that we had a bug on the following line inside GoogleAdapter.cs (line 116) where Arguments was null and we did not have the ? operator)

        if(actionPayload.Inputs.FirstOrDefault()?.Arguments?.FirstOrDefault()?.Name == "OPTION")

After that when trying to run the sample bot testing via the Actions On Google simulator, I get the following error:

API Version 2: Failed to parse JSON response string with 'INVALID_ARGUMENT' error: "payload: Cannot find field.".

Am I doing something wrong? Should this be working?

Thanks

**Comment by garypretty** [comment]
Hi. Thanks for reaching out. The Google adapter is in development at the moment, but I am hoping to release the first version this week. Keep an eye out for it in the next day or so!

I will check your issue out though. Can you provide some more details about how you have configured your action please?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by damadei** [comment]
Hi @garypretty, thanks a lot for the quick response!

I'm using the sample bot and have configured my action this way:

{
  "actions": [
    {
      "description": "Default Welcome Intent",
      "name": "MAIN",
      "fulfillment": {
        "conversationName": "TesteConversation"
      },
      "intent": {
        "name": "actions.intent.MAIN",
        "trigger": {
          "queryPatterns": [
            "falar com Teste Bot"
          ]
        }
      }
    }
  ],
  "conversations": {
    "TesteConversation": {
      "name": "TesteConversation",
      "url": "https://2edde055.ngrok.io/api/actionrequests"
    }
  },
  "locale": "pt-br"
}

**Comment by garypretty** [comment]
@damadei ok, thanks. I will take a look over the next couple of days as I am finishing up the adapter and come back to you!

**Comment by damadei** [comment]
@garypretty, I was able to use the adapter after following the action registration instructions and also after removing the piece of code that sets the Audio response along with the google card. Maybe we should fix that in the sample code.

**Comment by garypretty** [comment]
@damadei Thanks for this I will check it out and try and repro.  Appreciate the feedback!
