### ISSUE TITLE
Issue rendering cards

### ISSUE THREAD

**Issue by eduardaalonso** [BotBuilderCommunity/botbuilder-community-dotnet#57]
Hi, BotBuilderCommunity!

I'm getting the following error when trying to render cards on the Actions on Google Simulator:

`expected_inputs[0].input_prompt.rich_initial_prompt.items[0].simple_response: 'display_text' must be set or 'ssml' must have a valid display rendering.`

The error is the same for any card, except for the Signin, which prompts the bot to respond: "PLACEHOLDER_FOR_SIGN_IN"

Below is the code used to render the hero card:

```javascript
function createHeroCard(session) {
    return new builder.HeroCard(session)
        .title('BotFramework Hero Card')
        .subtitle('Your bots — wherever your users are talking')
        .text('Build and connect intelligent bots to interact with your users.')
        .images([
            builder.CardImage.create(session, 'https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg')
        ])
        .buttons([
            builder.CardAction.openUrl(session, 'https://docs.microsoft.com/bot-framework/', 'Get Started')
        ]);
}
```
The cards are correctly rendered on Azure's Web Chat. 

I can't seem to find the issue here, what can I do to make it work properly?

**Comment by garypretty** [comment]
Hi @eduardaalonso.  Which adapter / bridge are you using to surface your bot through a Google Action?  We have an adapter for Google coming, but it is for .NET bots and isn't yet finished.  If you are using the Capgemini Google bridge then you are probably best posting this issue within their GitHub repo.
