### ISSUE TITLE
Add recently deprecated .NET AzureTableStorage

### ISSUE THREAD

**Issue by garypretty** [BotBuilderCommunity/botbuilder-community-dotnet#6]
Add the deprecated code from the botbuilder-dotnet repo - the JS version has just been added to the community repo.

**Comment by szul** [comment]
@garypretty Is this a done deal on the dotnet side too? Shame.

**Comment by garypretty** [comment]
@szul looks that way. I went and checked when you committed the JS version.

**Comment by cleemullins** [comment]
The issues we kept running into were becoming overwhelming. The implemention here, for example, bumps into all of the Table store limits on rows and has non-standard handling of eTag semantics. 

This results in unexpected behaviors at random times - resulting in "it worked during testing, but failed in production" problems. 

For this reason, we believe CosmosDB and/or BlobStorage provide a more predictable storage model. A more robust table storage implementation is needed, and as we didn't have time to do that, we cut the feature.

**Comment by garypretty** [comment]
@cleemullins thanks for the insight here Chris. I have been slowly coming to the opinion that we shouldnt take this on anyway. I'm going to close this for now and it can be reopened if people do disagree.
