### ISSUE TITLE
List Support?

### ISSUE THREAD

**Issue by damadei** [BotBuilderCommunity/botbuilder-community-dotnet#73]
Hi all,

Do we have plans to support List Responses as part of the adapter?

I'd like to return a list with options to be selected by the user however seems that this is not supported nowadays.

Thanks
Daniel

**Comment by garypretty** [comment]
@damadei This is something I would like to support soon. I just need to find some time to add it.  The next release will add MVC support to the adapters, to bring them in line with the core SDK. Then after that I will start adding broader support for the Google adapter.

**Comment by garypretty** [comment]
@damadei Just a quick update on this.  I have a new preview for the Google adapter coming out in the next 24 hours (providing everything goes well 👍 ). This includes support for list / carousel / table card etc. plus updated documentation!  It would be great to get your feedback.
Sorry it took so long!

**Comment by garypretty** [comment]
@damadei - I have now made the preview available via MyGet, which includes both list and carousel support (along with more!) with all new documentation - you can find the updated docs, which detail how to get access to the preview package here -> https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/feature/google-adapter-refactor/libraries/Bot.Builder.Community.Adapters.Google/README.md.  

Closing this issue now that this is available - please do let me know if you have any feedback though.
