### ISSUE TITLE
Could not install the package

### ISSUE THREAD

**Issue by ajaypaulfrancis** [BotBuilderCommunity/botbuilder-community-dotnet#76]
Could not install package 'Bot.Builder.Community.Dialogs.FormFlow 4.3.10'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

Is it because am using a higher version of .NetFramework?

**Comment by EricDahlvang** [comment]
The minimum target framework is v4.6.1.

**Comment by garypretty** [comment]
Closing this - let us know if the above answer didn't resolve your issue.
