### ISSUE TITLE
Spell Check Middleware for other languages

### ISSUE THREAD

**Issue by Old-T** [BotBuilderCommunity/botbuilder-community-dotnet#8]
Hi,
How do I make the Spell Check to use swedish dictionary?

// Tommy

**Comment by jamesemann** [comment]
I'll look at this later today 👍 

Swedish is supported https://docs.microsoft.com/en-us/azure/cognitive-services/bing-spell-check/bing-spell-check-supported-languages

**Comment by garypretty** [comment]
@jamesemann can you reflect any changes in the branch tracking latest as well please?

**Comment by jamesemann** [comment]
I've added this enhancement [here](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/issue8-spellcheck-otherlangs/libraries/Bot.Builder.Community.Middleware.SpellCheck) and should be merged in the next day or so.

@garypretty I've created two PR's for master and the daily tracking branch. Would you be able to review at your convenience

**Comment by jamesemann** [comment]
@Old-T this has been implemented and will be available once the package has been indexed at 👉https://www.nuget.org/packages/Bot.Builder.Community.Middleware.SpellCheck/1.0.61

Thanks for the feature suggestion and please let me know if you have any issues with it.
