### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by mzucca** [BotBuilderCommunity/botbuilder-community-dotnet#84]
Hi to all,
I wrote some, minimal, code to improve the google adapter (capturing the intent and entities) 
If you want I can share my, smal, piece of code

**Comment by garypretty** [comment]
Yes, please share it with us and we can look to incorporate it.

**Comment by mzucca** [comment]
Hi Gary
[Changes.zip](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/files/3064530/Changes.zip)

added a zip file with all my modifications (very few of them). I really did not so much but if you want feel free to incorporate it. You've done an amazing job. I'll use it in some of the experiments we're working on and I'll be really happy if I can help a little bit.

Let me know if I can help in any way

bye
.mario

**Comment by garypretty** [comment]
@mzucca This looks great.  I might amend some of the bits around the Google request type / activity types to ensure I can keep some consistency with Alexa, but I will be looking to get this integrated over the next few days hopefully. Thanks again!
