### ISSUE TITLE
The skill end-point is not accepting valid signed requests

### ISSUE THREAD

**Issue by GhostAtom** [BotBuilderCommunity/botbuilder-community-dotnet#87]
I have an issue while submitting my skill to Amazon functionnal test. Few days ago it was working.

> The skill end-point is not accepting valid signed requests. Please make sure that your signature URL validation is correct.
Documentation Help:
Verifying the signature certificate URL: [Click here](https://developer.amazon.com/docs/custom-skills/host-a-custom-skill-as-a-web-service.html#cert-verify-signature-certificate-url)

I use validation option `options.AlexaOptions.ValidateIncomingAlexaRequests = true;`
Any idea for a fix?

**Comment by GhostAtom** [comment]
@garypretty I don't know if you can help on that issue? thank you in advance

**Comment by garypretty** [comment]
@GhostAtom Hi. Apologies for not coming back on this until now - did you resolve your issue?

**Comment by garypretty** [comment]
Closing this - please reopen if still experiencing an issue.
