### ISSUE TITLE
Remove community Typing due to duplicating existing SDK functionality

### ISSUE THREAD

**Issue by garypretty** [BotBuilderCommunity/botbuilder-community-dotnet#9]
@jamesemann @arafattehsin There is already a ShowTyping middleware component in the .NET SDK - what extra does the community middleware provide?  If nothing, then I suggest we remove this.

https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/ShowTypingMiddleware.cs

**Comment by jamesemann** [comment]
Yes I agree - this was ported from my old V3 code and the sdk middleware does the same thing, so happy to remove this. will do so in the next few days
