### ISSUE TITLE
http://docs.botframework.com/images/bot_icon.png is a dead link

### ISSUE THREAD

**Issue by EricDahlvang** [BotBuilderCommunity/botbuilder-community-dotnet#98]
docs.botframework.com has been taken down.  The bot_icon.png no longer resolves to a png file.

**Comment by arafattehsin** [comment]
Hi @EricDahlvang I noticed that we're only using this Url in one of our build props. Are you referring to the same?

**Comment by EricDahlvang** [comment]
Yes, that is what I'm referring to.

**Comment by arafattehsin** [comment]
Thanks. I have added a different (working) link.
